#!/bin/bash
# Copyright (c) 2020 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
  
BPF_GPL_DIR='./bpf-gpl'
BPF_APACHE_DIR='./bpf-apache'
copyright_owner="Tigera, Inc"
year=$(date +'%Y')
copyright_re="Copyright (c) .*${year}.* ${copyright_owner}. All rights reserved."

GPL_LICENCE_TEXT=$'This program is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version'

APACHE_LICENCE_TEXT=$'Licensed under the Apache License, Version 2.0 (the "License");'

files_without_copyright=()
files_without_license_gpl=()
files_without_license_apache=()

gpl_license_check_failed=false
apache_license_check_failed=false
copyright_check_failed=false

files=$(find $BPF_GPL_DIR -name "*.c" -o -name "*.h")
echo "Checking C files for copyright, GPL/Apache license statements..."
for file in $files; do
        files_without_copyright+=($(grep -L  "$copyright_re" $file))
        files_without_license_gpl+=($(grep -L  "$GPL_LICENCE_TEXT" $file))
done

files=$(find $BPF_APACHE_DIR -name "*.c" -o -name "*.h")
for file in $files; do
        files_without_copyright+=($(grep -L  "$copyright_re" $file))
        files_without_license_apache+=($(grep -L  "$APACHE_LICENCE_TEXT" $file))
done

for file in "${files_without_license_gpl[@]}"; do
        echo "File is missing GPL license:" `basename $file`
        gpl_license_check_failed=true
done
for file in "${files_without_copyright[@]}"; do
        echo "File is missing ${copyright_owner} copyright:" `basename $file`
        copyright_check_failed=true
done
for file in "${files_without_license_apache[@]}"; do
        echo "File is missing Apache license:" `basename $file`
        apache_license_check_failed=true
done

if $copyright_check_failed; then
  echo
  echo "Copyright statement should match:"
  echo
  echo "  # ${copyright_re}"
  echo "Example for new files:"
  echo "  # Copyright (c) ${year} ${copyright_owner}. All rights reserved."
  echo "Example for updated files (use commas and year ranges):"
  echo "  # Copyright (c) 2012,2015-${year} ${copyright_owner}. All rights reserved."
  echo 
fi

if $gpl_license_check_failed; then
  echo
  echo "GPL license header should be"
  echo 
  echo // This program is free software';' you can redistribute it and/or modify
  echo // it under the terms of the GNU General Public License as published by
  echo // the Free Software Foundation';' either version 2 of the License, or
  echo // '('at your option')' any later version.
  echo //
  echo // This program is distributed in the hope that it will be useful,
  echo // but WITHOUT ANY WARRANTY';' without even the implied warranty of
  echo // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  echo // GNU General Public License for more details.
  echo //
  echo // You should have received a copy of the GNU General Public License along
  echo // with this program';' if not, write to the Free Software Foundation, Inc.,
  echo // 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  echo 
fi

if $apache_license_check_failed; then
  echo
  echo "Apache license header should be:"
  echo
  echo '// Licensed under the Apache License, Version 2.0 (the "License");'
  echo '// you may not use this file except in compliance with the License.'
  echo '// You may obtain a copy of the License at'
  echo '//'
  echo '//     http://www.apache.org/licenses/LICENSE-2.0'
  echo '//'
  echo '// Unless required by applicable law or agreed to in writing, software'
  echo '// distributed under the License is distributed on an "AS IS" BASIS,'
  echo '// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
  echo '// See the License for the specific language governing permissions and'
  echo '// limitations under the License.'
  echo 
fi
if $gpl_license_check_failed || $copyright_check_failed \
   $apache_license_check_failed; then
        exit 1
fi

