inpackage: False
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/projectcalico/calico/goldmane/pkg/client:
    config:
      pkgname: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      FlowsClient:
