// Copyright (c) 2026 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by felix/labelindex/gen/endpointdata; DO NOT EDIT.

package labelindex

import (
	"iter"

	"github.com/projectcalico/calico/felix/ip"
	"github.com/projectcalico/calico/felix/labelindex/ipsetmember"
	"github.com/projectcalico/calico/lib/std/uniquelabels"
	"github.com/projectcalico/calico/lib/std/uniquestr"
	"github.com/projectcalico/calico/libcalico-go/lib/backend/model"
	"github.com/projectcalico/calico/libcalico-go/lib/set"
)

// epV4Ports0Parents0 is the counted variant for V4, Ports0, Parents0.
type epV4Ports0Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports0Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV4Ports0Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports0Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports0Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports0Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV4Ports0Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV4Ports0Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV4Ports0Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports0Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports0Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports0Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports0Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports0Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports0Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports0Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}

	return true
}

// epV4Ports0Parents1 is the counted variant for V4, Ports0, Parents1.
type epV4Ports0Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports0Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports0Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports0Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports0Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports0Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV4Ports0Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV4Ports0Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV4Ports0Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports0Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports0Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports0Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports0Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports0Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports0Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports0Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epV4Ports0Parents2 is the counted variant for V4, Ports0, Parents2.
type epV4Ports0Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports0Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports0Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports0Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports0Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports0Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV4Ports0Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV4Ports0Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV4Ports0Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports0Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports0Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports0Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports0Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports0Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports0Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports0Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epV4Ports1Parents0 is the counted variant for V4, Ports1, Parents0.
type epV4Ports1Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	ports  [1]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports1Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV4Ports1Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports1Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports1Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports1Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
	}
	return buf
}

func (d *epV4Ports1Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV4Ports1Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV4Ports1Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports1Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports1Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports1Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports1Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports1Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports1Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports1Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epV4Ports1Parents1 is the counted variant for V4, Ports1, Parents1.
type epV4Ports1Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	ports   [1]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports1Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports1Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports1Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports1Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports1Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
	}
	return buf
}

func (d *epV4Ports1Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV4Ports1Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV4Ports1Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports1Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports1Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports1Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports1Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports1Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports1Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports1Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV4Ports1Parents2 is the counted variant for V4, Ports1, Parents2.
type epV4Ports1Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	ports   [1]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports1Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports1Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports1Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports1Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports1Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
	}
	return buf
}

func (d *epV4Ports1Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV4Ports1Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV4Ports1Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports1Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports1Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports1Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports1Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports1Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports1Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports1Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV4Ports2Parents0 is the counted variant for V4, Ports2, Parents0.
type epV4Ports2Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	ports  [2]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports2Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV4Ports2Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports2Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports2Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports2Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		}
	}
	return buf
}

func (d *epV4Ports2Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV4Ports2Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV4Ports2Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports2Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports2Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports2Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports2Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports2Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports2Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports2Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epV4Ports2Parents1 is the counted variant for V4, Ports2, Parents1.
type epV4Ports2Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	ports   [2]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports2Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports2Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports2Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports2Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports2Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		}
	}
	return buf
}

func (d *epV4Ports2Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV4Ports2Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV4Ports2Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports2Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports2Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports2Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports2Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports2Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports2Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports2Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV4Ports2Parents2 is the counted variant for V4, Ports2, Parents2.
type epV4Ports2Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	ports   [2]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV4Ports2Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV4Ports2Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV4Ports2Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV4Ports2Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	return buf
}

func (d *epV4Ports2Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		}
	}
	return buf
}

func (d *epV4Ports2Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV4Ports2Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV4Ports2Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV4Ports2Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV4Ports2Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV4Ports2Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV4Ports2Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV4Ports2Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV4Ports2Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV4Ports2Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports0Parents0 is the counted variant for V6, Ports0, Parents0.
type epV6Ports0Parents0 struct {
	labels uniquelabels.Map
	v6     [1]ip.V6Addr
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports0Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV6Ports0Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports0Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports0Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports0Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV6Ports0Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV6Ports0Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV6Ports0Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports0Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports0Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports0Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports0Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports0Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports0Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports0Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}

	return true
}

// epV6Ports0Parents1 is the counted variant for V6, Ports0, Parents1.
type epV6Ports0Parents1 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports0Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports0Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports0Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports0Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports0Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV6Ports0Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV6Ports0Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV6Ports0Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports0Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports0Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports0Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports0Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports0Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports0Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports0Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports0Parents2 is the counted variant for V6, Ports0, Parents2.
type epV6Ports0Parents2 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports0Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports0Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports0Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports0Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports0Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epV6Ports0Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV6Ports0Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV6Ports0Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports0Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports0Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports0Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports0Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports0Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports0Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports0Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports1Parents0 is the counted variant for V6, Ports1, Parents0.
type epV6Ports1Parents0 struct {
	labels uniquelabels.Map
	v6     [1]ip.V6Addr
	ports  [1]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports1Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV6Ports1Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports1Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports1Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports1Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epV6Ports1Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV6Ports1Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV6Ports1Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports1Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports1Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports1Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports1Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports1Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports1Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports1Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epV6Ports1Parents1 is the counted variant for V6, Ports1, Parents1.
type epV6Ports1Parents1 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	ports   [1]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports1Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports1Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports1Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports1Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports1Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epV6Ports1Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV6Ports1Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV6Ports1Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports1Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports1Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports1Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports1Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports1Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports1Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports1Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports1Parents2 is the counted variant for V6, Ports1, Parents2.
type epV6Ports1Parents2 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	ports   [1]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports1Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports1Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports1Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports1Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports1Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epV6Ports1Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV6Ports1Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV6Ports1Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports1Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports1Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports1Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports1Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports1Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports1Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports1Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports2Parents0 is the counted variant for V6, Ports2, Parents0.
type epV6Ports2Parents0 struct {
	labels uniquelabels.Map
	v6     [1]ip.V6Addr
	ports  [2]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports2Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epV6Ports2Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports2Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports2Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports2Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epV6Ports2Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epV6Ports2Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epV6Ports2Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports2Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports2Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports2Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports2Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports2Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports2Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports2Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epV6Ports2Parents1 is the counted variant for V6, Ports2, Parents1.
type epV6Ports2Parents1 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	ports   [2]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports2Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports2Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports2Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports2Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports2Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epV6Ports2Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epV6Ports2Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epV6Ports2Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports2Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports2Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports2Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports2Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports2Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports2Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports2Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epV6Ports2Parents2 is the counted variant for V6, Ports2, Parents2.
type epV6Ports2Parents2 struct {
	labels  uniquelabels.Map
	v6      [1]ip.V6Addr
	ports   [2]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epV6Ports2Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epV6Ports2Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epV6Ports2Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epV6Ports2Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epV6Ports2Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epV6Ports2Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epV6Ports2Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epV6Ports2Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epV6Ports2Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epV6Ports2Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epV6Ports2Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epV6Ports2Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epV6Ports2Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epV6Ports2Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epV6Ports2Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts0Parents0 is the counted variant for Dual, Ports0, Parents0.
type epDualPorts0Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	v6     [1]ip.V6Addr
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts0Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epDualPorts0Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts0Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts0Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts0Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epDualPorts0Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epDualPorts0Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epDualPorts0Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts0Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts0Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts0Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts0Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts0Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts0Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts0Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}

	return true
}

// epDualPorts0Parents1 is the counted variant for Dual, Ports0, Parents1.
type epDualPorts0Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts0Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts0Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts0Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts0Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts0Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epDualPorts0Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epDualPorts0Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epDualPorts0Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts0Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts0Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts0Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts0Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts0Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts0Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts0Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts0Parents2 is the counted variant for Dual, Ports0, Parents2.
type epDualPorts0Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts0Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts0Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts0Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts0Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts0Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	// No ports.
	return buf
}

func (d *epDualPorts0Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epDualPorts0Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epDualPorts0Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts0Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts0Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts0Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts0Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts0Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts0Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts0Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}

	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts1Parents0 is the counted variant for Dual, Ports1, Parents0.
type epDualPorts1Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	v6     [1]ip.V6Addr
	ports  [1]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts1Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epDualPorts1Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts1Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts1Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts1Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epDualPorts1Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epDualPorts1Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epDualPorts1Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts1Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts1Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts1Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts1Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts1Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts1Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts1Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epDualPorts1Parents1 is the counted variant for Dual, Ports1, Parents1.
type epDualPorts1Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	ports   [1]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts1Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts1Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts1Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts1Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts1Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epDualPorts1Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epDualPorts1Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epDualPorts1Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts1Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts1Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts1Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts1Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts1Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts1Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts1Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts1Parents2 is the counted variant for Dual, Ports1, Parents2.
type epDualPorts1Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	ports   [1]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts1Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts1Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts1Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts1Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts1Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	if port, emit, ok := portHandleMatches(d.ports[0], name, proto); ok {
		buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
		buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
	}
	return buf
}

func (d *epDualPorts1Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epDualPorts1Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epDualPorts1Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts1Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts1Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts1Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts1Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts1Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts1Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts1Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts2Parents0 is the counted variant for Dual, Ports2, Parents0.
type epDualPorts2Parents0 struct {
	labels uniquelabels.Map
	v4     [1]ip.V4Addr
	v6     [1]ip.V6Addr
	ports  [2]portHandle
	cache  set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts2Parents0) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}

	return uniquestr.Handle{}, false
}

func (d *epDualPorts2Parents0) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts2Parents0) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts2Parents0) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts2Parents0) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epDualPorts2Parents0) EachParent(yield func(*npParentData) bool) {
	// No parents.
}

func (d *epDualPorts2Parents0) HasParent(parent *npParentData) bool {
	return false
}

func (d *epDualPorts2Parents0) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts2Parents0) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts2Parents0) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts2Parents0) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts2Parents0) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts2Parents0) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts2Parents0) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts2Parents0)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}

	return true
}

// epDualPorts2Parents1 is the counted variant for Dual, Ports2, Parents1.
type epDualPorts2Parents1 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	ports   [2]portHandle
	parents [1]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts2Parents1) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts2Parents1) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts2Parents1) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts2Parents1) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts2Parents1) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epDualPorts2Parents1) EachParent(yield func(*npParentData) bool) {
	if !yield(d.parents[0]) {
		return
	}
}

func (d *epDualPorts2Parents1) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent
}

func (d *epDualPorts2Parents1) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts2Parents1) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts2Parents1) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts2Parents1) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts2Parents1) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts2Parents1) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts2Parents1) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts2Parents1)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

// epDualPorts2Parents2 is the counted variant for Dual, Ports2, Parents2.
type epDualPorts2Parents2 struct {
	labels  uniquelabels.Map
	v4      [1]ip.V4Addr
	v6      [1]ip.V6Addr
	ports   [2]portHandle
	parents [2]*npParentData
	cache   set.Adaptive[string]
}

// GetHandle is inlined per-variant so the hot selector-eval path
// doesn't allocate the iter.Seq closure that a generic walker would.
func (d *epDualPorts2Parents2) GetHandle(name uniquestr.Handle) (uniquestr.Handle, bool) {
	if h, ok := d.labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[0].labels.GetHandle(name); ok {
		return h, true
	}
	if h, ok := d.parents[1].labels.GetHandle(name); ok {
		return h, true
	}
	return uniquestr.Handle{}, false
}

func (d *epDualPorts2Parents2) OwnLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return d.labels.AllHandles()
}

func (d *epDualPorts2Parents2) AllOwnAndParentLabelHandles() iter.Seq2[uniquestr.Handle, uniquestr.Handle] {
	return allOwnAndParentLabelHandles(d.labels, d.EachParent)
}

func (d *epDualPorts2Parents2) AppendCIDROrIPMembers(buf []ipsetmember.IPSetMember) []ipsetmember.IPSetMember {
	buf = append(buf, ipsetmember.MakeSingleIPv4(d.v4[0]))
	buf = append(buf, ipsetmember.MakeSingleIPv6(d.v6[0]))
	return buf
}

func (d *epDualPorts2Parents2) AppendIPPortMembers(buf []ipsetmember.IPSetMember,
	name string, proto ipsetmember.Protocol) []ipsetmember.IPSetMember {
	for _, h := range d.ports {
		if port, emit, ok := portHandleMatches(h, name, proto); ok {
			buf = append(buf, ipsetmember.MakeIPPortProtoV4(d.v4[0], port, emit))
			buf = append(buf, ipsetmember.MakeIPPortProtoV6(d.v6[0], port, emit))
		}
	}
	return buf
}

func (d *epDualPorts2Parents2) EachParent(yield func(*npParentData) bool) {
	for _, p := range d.parents {
		if !yield(p) {
			return
		}
	}
}

func (d *epDualPorts2Parents2) HasParent(parent *npParentData) bool {
	return d.parents[0] == parent || d.parents[1] == parent
}

func (d *epDualPorts2Parents2) AddMatchingIPSetID(id string)       { d.cache.Add(id) }
func (d *epDualPorts2Parents2) RemoveMatchingIPSetID(id string)    { d.cache.Discard(id) }
func (d *epDualPorts2Parents2) NumMatchingIPSetIDs() int           { return d.cache.Len() }
func (d *epDualPorts2Parents2) MatchingIPSetIDs() iter.Seq[string] { return d.cache.All() }
func (d *epDualPorts2Parents2) ClearMatchingIPSetIDs()             { d.cache.Clear() }
func (d *epDualPorts2Parents2) MatchingIPSetIDsString() string     { return d.cache.String() }

func (d *epDualPorts2Parents2) EqualTo(other endpointData) bool {
	o, ok := other.(*epDualPorts2Parents2)
	if !ok {
		return false
	}
	if !d.labels.Equals(o.labels) {
		return false
	}
	if d.v4 != o.v4 || d.v6 != o.v6 {
		return false
	}
	if d.ports != o.ports {
		return false
	}
	if d.parents != o.parents {
		return false
	}
	return true
}

func newCountedEndpointData(
	labels uniquelabels.Map,
	shape cidrShape,
	v4 ip.V4Addr,
	v6 ip.V6Addr,
	ports []model.EndpointPort,
	parents []*npParentData,
) endpointData {
	switch shape {
	case cidrShapeV4:
		switch len(ports) {
		case 0:
			switch len(parents) {
			case 0:
				return &epV4Ports0Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4},
				}
			case 1:
				return &epV4Ports0Parents1{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV4Ports0Parents2{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 1:
			switch len(parents) {
			case 0:
				return &epV4Ports1Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4},
					ports:  [1]portHandle{internEndpointPort(ports[0])},
				}
			case 1:
				return &epV4Ports1Parents1{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV4Ports1Parents2{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 2:
			switch len(parents) {
			case 0:
				return &epV4Ports2Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4},
					ports:  [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
				}
			case 1:
				return &epV4Ports2Parents1{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV4Ports2Parents2{
					labels:  labels,
					v4:      [1]ip.V4Addr{v4},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		}
	case cidrShapeV6:
		switch len(ports) {
		case 0:
			switch len(parents) {
			case 0:
				return &epV6Ports0Parents0{
					labels: labels,
					v6:     [1]ip.V6Addr{v6},
				}
			case 1:
				return &epV6Ports0Parents1{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV6Ports0Parents2{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 1:
			switch len(parents) {
			case 0:
				return &epV6Ports1Parents0{
					labels: labels,
					v6:     [1]ip.V6Addr{v6},
					ports:  [1]portHandle{internEndpointPort(ports[0])},
				}
			case 1:
				return &epV6Ports1Parents1{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV6Ports1Parents2{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 2:
			switch len(parents) {
			case 0:
				return &epV6Ports2Parents0{
					labels: labels,
					v6:     [1]ip.V6Addr{v6},
					ports:  [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
				}
			case 1:
				return &epV6Ports2Parents1{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epV6Ports2Parents2{
					labels:  labels,
					v6:      [1]ip.V6Addr{v6},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		}
	case cidrShapeDual:
		switch len(ports) {
		case 0:
			switch len(parents) {
			case 0:
				return &epDualPorts0Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
				}
			case 1:
				return &epDualPorts0Parents1{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epDualPorts0Parents2{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 1:
			switch len(parents) {
			case 0:
				return &epDualPorts1Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports: [1]portHandle{internEndpointPort(ports[0])},
				}
			case 1:
				return &epDualPorts1Parents1{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epDualPorts1Parents2{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports:   [1]portHandle{internEndpointPort(ports[0])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		case 2:
			switch len(parents) {
			case 0:
				return &epDualPorts2Parents0{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports: [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
				}
			case 1:
				return &epDualPorts2Parents1{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [1]*npParentData{parents[0]},
				}
			case 2:
				return &epDualPorts2Parents2{
					labels: labels,
					v4:     [1]ip.V4Addr{v4}, v6: [1]ip.V6Addr{v6},
					ports:   [2]portHandle{internEndpointPort(ports[0]), internEndpointPort(ports[1])},
					parents: [2]*npParentData{parents[0], parents[1]},
				}
			}
		}
	}
	panic("newCountedEndpointData: unhandled shape; newEndpointData should have routed to general")
}
