// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

// ServiceClusterIPBlockApplyConfiguration represents a declarative configuration of the ServiceClusterIPBlock type for use
// with apply.
//
// ServiceClusterIPBlock represents a single allowed ClusterIP CIDR block.
type ServiceClusterIPBlockApplyConfiguration struct {
	CIDR *string `json:"cidr,omitempty"`
}

// ServiceClusterIPBlockApplyConfiguration constructs a declarative configuration of the ServiceClusterIPBlock type for use with
// apply.
func ServiceClusterIPBlock() *ServiceClusterIPBlockApplyConfiguration {
	return &ServiceClusterIPBlockApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *ServiceClusterIPBlockApplyConfiguration) WithCIDR(value string) *ServiceClusterIPBlockApplyConfiguration {
	b.CIDR = &value
	return b
}
