global_job_config:
  secrets:
    - name: docker-hub
    - name: google-service-account-for-gce
    - name: go-build-cache-gcp-s3-credentials
  env_vars:
    - name: GOOGLE_PROJECT
      value: unique-caldron-775
    - name: GCS_BUILD_CACHE_BUCKET
      value: calico-transient-build-artifacts-europe-west3
    - name: BUILDKIT_PROGRESS
      value: plain
    - name: SEMAPHORE_AGENT_UPLOAD_JOB_LOGS
      value: when-trimmed
  prologue:
    commands:
      - export CALICO_DIR_NAME=${SEMAPHORE_GIT_DIR}
      - export GCS_CACHE_DIR=gs://$GCS_BUILD_CACHE_BUCKET/cache/${CALICO_DIR_NAME}
      - export GCS_WORKFLOW_DIR=gs://$GCS_BUILD_CACHE_BUCKET/workflow/${SEMAPHORE_WORKFLOW_ID}
      - export GOOGLE_APPLICATION_CREDENTIALS=$HOME/secrets/secret.google-service-account-key.json
      - |-
        if [[ $(uname -m) != "x86_64" || -n "$ARCH" ]]; then
          echo "Non-x86_64 build: $(uname -m) / $ARCH";
          export BUILD_CACHE_GROUP=$BUILD_CACHE_GROUP-$(uname -m)-$ARCH;
        fi
      - gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS" || true
      - gcloud config set project ${GOOGLE_PROJECT} || true
      - echo $DOCKERHUB_PASSWORD | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  epilogue:
    commands:
      - cd "$CALICO_DIR"
      - .semaphore/publish-artifacts
