FROM arm64v8/alpine:3.18
RUN apk add --no-cache \
    python3  \
    py3-pip \
    netcat-openbsd
COPY udpping.sh tcpping.sh responder.py /code/
WORKDIR /code/
RUN chmod +x udpping.sh && chmod +x tcpping.sh
CMD ["python", "responder.py"]
