// Copyright (c) 2021 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	projectcalico "github.com/projectcalico/apiserver/pkg/apis/projectcalico"
)

// FakeBGPConfigurations implements BGPConfigurationInterface
type FakeBGPConfigurations struct {
	Fake *FakeProjectcalico
}

var bgpconfigurationsResource = schema.GroupVersionResource{Group: "projectcalico.org", Version: "", Resource: "bgpconfigurations"}

var bgpconfigurationsKind = schema.GroupVersionKind{Group: "projectcalico.org", Version: "", Kind: "BGPConfiguration"}

// Get takes name of the bGPConfiguration, and returns the corresponding bGPConfiguration object, and an error if there is any.
func (c *FakeBGPConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *projectcalico.BGPConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bgpconfigurationsResource, name), &projectcalico.BGPConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.BGPConfiguration), err
}

// List takes label and field selectors, and returns the list of BGPConfigurations that match those selectors.
func (c *FakeBGPConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *projectcalico.BGPConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bgpconfigurationsResource, bgpconfigurationsKind, opts), &projectcalico.BGPConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectcalico.BGPConfigurationList{ListMeta: obj.(*projectcalico.BGPConfigurationList).ListMeta}
	for _, item := range obj.(*projectcalico.BGPConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bGPConfigurations.
func (c *FakeBGPConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bgpconfigurationsResource, opts))
}

// Create takes the representation of a bGPConfiguration and creates it.  Returns the server's representation of the bGPConfiguration, and an error, if there is any.
func (c *FakeBGPConfigurations) Create(ctx context.Context, bGPConfiguration *projectcalico.BGPConfiguration, opts v1.CreateOptions) (result *projectcalico.BGPConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bgpconfigurationsResource, bGPConfiguration), &projectcalico.BGPConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.BGPConfiguration), err
}

// Update takes the representation of a bGPConfiguration and updates it. Returns the server's representation of the bGPConfiguration, and an error, if there is any.
func (c *FakeBGPConfigurations) Update(ctx context.Context, bGPConfiguration *projectcalico.BGPConfiguration, opts v1.UpdateOptions) (result *projectcalico.BGPConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bgpconfigurationsResource, bGPConfiguration), &projectcalico.BGPConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.BGPConfiguration), err
}

// Delete takes name of the bGPConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeBGPConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(bgpconfigurationsResource, name), &projectcalico.BGPConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBGPConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bgpconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &projectcalico.BGPConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched bGPConfiguration.
func (c *FakeBGPConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectcalico.BGPConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgpconfigurationsResource, name, pt, data, subresources...), &projectcalico.BGPConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectcalico.BGPConfiguration), err
}
