#!/bin/sh
echo calico/node ${NODE_VERSION}
confd -version
bird --version
echo -n "libnetwork-plugin: "
libnetwork-plugin -v
echo -n "calico-bgp-daemon: "
calico-bgp-daemon -v
echo ""
echo "Felix:"
calico-felix --version
