#!/bin/sh
exec 2>&1
# Felix doesn't understand HOSTNAME, but the container exports it as a common
# interface. This ensures Felix gets the right hostname.
if [ ! -z $HOSTNAME ]; then
    export FELIX_FELIXHOSTNAME=$HOSTNAME
fi
export FELIX_ETCDADDR=$ETCD_AUTHORITY
export FELIX_ETCDENDPOINTS=$ETCD_ENDPOINTS
export FELIX_ETCDSCHEME=$ETCD_SCHEME
export FELIX_ETCDCAFILE=$ETCD_CA_CERT_FILE
export FELIX_ETCDKEYFILE=$ETCD_KEY_FILE
export FELIX_ETCDCERTFILE=$ETCD_CERT_FILE
exec calico-felix
