FROM ppc64le/busybox

LABEL maintainer "Tom Denham <tom@tigera.io>"

ADD dist-ppc64le/calico /opt/cni/bin/calico
ADD dist-ppc64le/flannel /opt/cni/bin/flannel
ADD dist-ppc64le/loopback /opt/cni/bin/loopback
ADD dist-ppc64le/host-local /opt/cni/bin/host-local
ADD dist-ppc64le/portmap /opt/cni/bin/portmap
ADD dist-ppc64le/calico-ipam /opt/cni/bin/calico-ipam
ADD k8s-install/scripts/install-cni.sh /install-cni.sh
ADD k8s-install/scripts/calico.conf.default /calico.conf.tmp

ENV PATH=$PATH:/opt/cni/bin
VOLUME /opt/cni
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/calico"]
