FROM s390x/busybox

LABEL maintainer "LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)"

ADD dist/s390x/calico /opt/cni/bin/calico
ADD dist/s390x/flannel /opt/cni/bin/flannel
ADD dist/s390x/loopback /opt/cni/bin/loopback
ADD dist/s390x/host-local /opt/cni/bin/host-local
ADD dist/s390x/portmap /opt/cni/bin/portmap
ADD dist/s390x/calico-ipam /opt/cni/bin/calico-ipam
ADD k8s-install/scripts/install-cni.sh /install-cni.sh
ADD k8s-install/scripts/calico.conf.default /calico.conf.tmp

ENV PATH=$PATH:/opt/cni/bin
VOLUME /opt/cni
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/calico"]
