FROM ppc64le/alpine:3.8

RUN mkdir -p /usr/local/bin
ADD flexvol/docker/flexvol.sh /usr/local/bin/
ADD bin/flexvol-ppc64le /usr/local/bin/flexvol

RUN chmod +x /usr/local/bin/flexvol.sh

ENTRYPOINT ["/usr/local/bin/flexvol.sh"]
