FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

LABEL maintainer "Casey Davenport <casey@tigera.io>"

ADD licenses/ /licenses
ADD LICENSE /licenses/

ADD bin/ppc64le/ /opt/cni/bin/
ADD k8s-install/scripts/install-cni.sh /install-cni.sh
ADD k8s-install/scripts/calico.conf.default /calico.conf.tmp

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/calico"]
