FROM arm32v7/alpine:3.12
MAINTAINER Marc Crébassa <aalaesar@gmail.com>

RUN apk --no-cache upgrade apk-tools

ADD bin/calicoctl-linux-armv7 /calicoctl

ENV CALICO_CTL_CONTAINER=TRUE
ENV PATH=$PATH:/

WORKDIR /root
ENTRYPOINT ["/calicoctl"]
