

  +--------------------------------+
  |      docker-build-images/      |
  | ubuntu-trusty-build.Dockerfile |
  +--------------------------------+
                   |
                   |
             docker| build
                   |
                   |
                   v
         +--------------------+      +------------------------+      +--------------+
         | trusty-build-image |      | calico-iptables-plugin |      | calico-felix |
         +--------------------+      +------------------------+      +--------------+
                            \                     |                    /
                             '------.     debian/build-debs    .------'
                                     \            |           /
                                      \           v          /
                                   +----------------------------+
                                   | Debian packages for Trusty |
                                   +----------------------------+




Targets:

calico-build/golang:
  docker-build-images/passwd
  docker-build-images/group
  docker-build-images/golang-build.Dockerfile

calico-build/trusty:
  docker-build-images/ubuntu-trusty-build.Dockerfile

calico-build/xenial:
  docker-build-images/ubuntu-xenial-build.Dockerfile

docker-build-images/passwd:
docker-build-images/group:

calico-build/centos7:
  docker-build-images/passwd
  docker-build-images/group
  docker-build-images/centos7-build.Dockerfile

calico-build/python:
  docker-build-images/passwd
  docker-build-images/group
  docker-build-images/pyi/Dockerfile

update-frozen-reqs:
  reqs files
  calico-build/python
  pip install reqs
  pip freeze > frozen reqs file

calico/felix:
  calico-iptables-plugin
  calico-felix
  <rootdir>/Dockerfile

env: (for development only)

trusty-deb:
  calico-iptables-plugin
  calico-felix
  debian/*
  calico-build/trusty
  run debian/build-debs in 'calico-build/trusty'

xenial-deb - same but for xenial

rpm:
  calico-iptables-plugin
  calico-felix
  rpm/*
  calico-build/centos7
  run rpm/build-rpms in 'calico-build/centos7'

protobuf:
  py file:
    run felixbackend.proto in 'calico/protoc'
  go file:
    run felixbackend.proto in 'calico/protoc'

vendor/glide stuff
update-tools
go-fmt
ut...
  calico-build/golang
  calico-build/python

calico-felix:
  Go files
  calico-build/golang
  run 'go build' in calico-build/golang

pyinstaller:
  calico-felix-<version>.tgz:
    calico-iptables-plugin
    calico-felix
    tar up those executables

# Release concerns
Felix now arch-dependent?

calico-iptables-plugin:
  Python files
  calico-build/python
  generate version.txt file
  in calico-build/python:
    run pip install
    run docker-build-images/pyi/run-pyinstaller.sh
