#!/bin/bash

set -e

# Run tests in parallel (-p), find tests recursively (-r).
ginkgo -randomizeAllSpecs -cover -p -r --skipPackage vendor

echo
echo '+==============+'
echo '| All coverage |'
echo '+==============+'
echo
find -iname '*.coverprofile' | xargs -I _ go tool cover -func=_

echo
echo '+==================+'
echo '| Missing coverage |'
echo '+==================+'
echo
find -iname '*.coverprofile' | xargs -I _ go tool cover -func=_ | grep -v '100.0%'

