#!/usr/bin/env bash

set -x
set -e

if [ -z "${EL_VERSION}" ]; then
  echo "EL_VERSION variable should be set"
  exit 1
fi

repo=`pwd`
pkg=`basename $repo`

if [ ${pkg} = networking-calico ]; then
    # networking-calico uses an OpenStack thing called PBR (Python
    # Build Reasonableness), which is responsible among other things
    # for automatically computing the Python package-level version.
    # It does this from the Git context (tags etc.), or from an
    # environment variable PBR_VERSION if Git context is not
    # available.  We have Git context here, but will remove that (with
    # --exclude-vcs) from the source tarball that we pass to rpmbuild,
    # so we calculate PBR_VERSION now and then add that to the
    # environment for rpmbuild.
    export PBR_VERSION=`python - <<'EOF'
import pbr.version
print pbr.version.VersionInfo('networking-calico').release_string()
EOF`
fi

mkdir -p /tmp/rpmbuild/BUILD \
         /tmp/rpmbuild/RPMS \
         /tmp/rpmbuild/SOURCES \
         /tmp/rpmbuild/SPECS\
         /tmp/rpmbuild/SRPMS

cd /tmp/rpmbuild

# Infer RPM spec and package names, and link the package spec into
# ../SPECS.
spec=`basename ${repo}/rpm/*.spec`
cd SPECS
cp -a ${repo}/rpm/$spec .

# Link patches into ../SOURCES.
cd ../SOURCES
for f in ${repo}/rpm/*; do ln -sf $f; done

cd /tmp
case ${pkg} in
    felix | networking-calico )
	# Infer the version that the spec wants to build.
	version=`grep Version: $spec | head -1 | awk '{print $2;}'`

	# Tar up the Git source, with the naming that rpmbuild expects.
	dir=${pkg}-${version}
	cp -a ${repo} $dir
	tar --exclude-vcs -czf /tmp/rpmbuild/SOURCES/${dir}.tar.gz $dir
	;;
    etcd3gw)
	curl https://nero-mirror.stanford.edu/pypi/packages/08/02/63d5eb103943ce18c38dd1b11a2d63e6ff7260d44067458e7faa092c2b9e/etcd3gw-0.2.4.tar.gz -o rpmbuild/SOURCES/etcd3gw-0.2.4.tar.gz
	;;
esac

# Build, and fix centos7 putting always '.centos7' in the rpm-name
cd rpmbuild
rpmbuild --target=$(uname -m) --define '_topdir '`pwd` --define "dist .${EL_VERSION}" -ba SPECS/${spec}
mkdir -p /code/dist/rpms-${EL_VERSION}/src
cp -r /tmp/rpmbuild/RPMS/* /code/dist/rpms-${EL_VERSION}/
cp -r /tmp/rpmbuild/SRPMS/* /code/dist/rpms-${EL_VERSION}/src/
