// Copyright (c) 2026 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cilanes

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const configPrefix = "e2e/config/"

// ResolveSets maps each distinct selection to a stable name. Two lanes claiming
// one name with different selections is CI drift.
func ResolveSets(lanes []Lane) (map[string]Lane, error) {
	sets := map[string]Lane{}
	for _, l := range lanes {
		if !l.RunsE2EBinary() {
			// run_tests.sh exits 1 on an e2e lane that selects nothing.
			if l.TestType == "k8s-e2e" && l.Area != "" {
				return nil, fmt.Errorf("%s (%s) runs the e2e binary but selects nothing", l.Name, l.Source)
			}
			continue
		}
		name, err := SetName(l)
		if err != nil {
			return nil, fmt.Errorf("%s (%s): %w", l.Name, l.Source, err)
		}
		if _, ok := sets[name]; !ok {
			sets[name] = l
		}
	}
	return sets, nil
}

// SetName is the lane's config path, relative to e2e/config and without the
// extension.
func SetName(l Lane) (string, error) {
	if !strings.HasPrefix(l.Config, configPrefix) {
		return "", fmt.Errorf("config %q is not under %s", l.Config, configPrefix)
	}
	return strings.TrimSuffix(strings.TrimPrefix(l.Config, configPrefix), ".yaml"), nil
}

// Write records the index and one file per set under dir.
func Write(dir string, lanes []Lane, specs map[string][]string) error {
	setsDir := filepath.Join(dir, "sets")
	if err := os.RemoveAll(setsDir); err != nil {
		return err
	}
	for name, list := range specs {
		path := filepath.Join(setsDir, filepath.FromSlash(name)+".txt")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		var body string
		if len(list) > 0 {
			body = strings.Join(list, "\n") + "\n"
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
	}

	var index strings.Builder
	index.WriteString("# Generated by `make gen-test-set`. Do not edit.\n")
	index.WriteString("# ci file | lane | test set | specs\n")
	for _, l := range lanes {
		set, count := "("+l.TestType+")", "-"
		if l.Area == "" {
			set = "(no tests)"
		}
		if l.RunsE2EBinary() {
			name, err := SetName(l)
			if err != nil {
				return err
			}
			set, count = name, fmt.Sprint(len(specs[name]))
		}
		fmt.Fprintf(&index, "%s | %s | %s | %s\n", l.Source, l.Name, set, count)
	}
	return os.WriteFile(filepath.Join(dir, "index.txt"), []byte(index.String()), 0o644)
}
