// Copyright (c) 2026 Tigera, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cilanes

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const configPrefix = "e2e/config/"

// ResolveSets maps each distinct selection to a stable name. Two lanes claiming
// one name with different selections is CI drift.
func ResolveSets(lanes []Lane) (map[string]Lane, error) {
	sets := map[string]Lane{}
	for _, l := range lanes {
		if !l.RunsE2EBinary() {
			continue
		}
		name, err := SetName(l)
		if err != nil {
			return nil, fmt.Errorf("%s (%s): %w", l.Name, l.Source, err)
		}
		prev, ok := sets[name]
		if ok && prev.Selection() != l.Selection() {
			return nil, fmt.Errorf("%q resolves to different selections in %s (%s: %s) and %s (%s: %s)",
				name, prev.Source, prev.Name, prev.Selection(), l.Source, l.Name, l.Selection())
		}
		if !ok {
			sets[name] = l
		}
	}
	return sets, nil
}

// SetName is the config path once a lane is converted, and a legacy/ name keyed
// off FUNCTIONAL_AREA while it still selects by regex.
func SetName(l Lane) (string, error) {
	if l.Config != "" {
		if !strings.HasPrefix(l.Config, configPrefix) {
			return "", fmt.Errorf("config %q is not under %s", l.Config, configPrefix)
		}
		return strings.TrimSuffix(strings.TrimPrefix(l.Config, configPrefix), ".yaml"), nil
	}
	if l.Area == "" {
		return "", fmt.Errorf("lane declares no %s", envArea)
	}
	area := strings.TrimSuffix(l.Area, filepath.Ext(l.Area))
	if l.PipelineDefault {
		return "legacy/" + area, nil
	}
	return "legacy/" + area + "/" + slug(l.Name), nil
}

var nonSlug = regexp.MustCompile(`[^a-z0-9]+`)

func slug(s string) string {
	return strings.Trim(nonSlug.ReplaceAllString(strings.ToLower(s), "-"), "-")
}

// Write records the index and one file per set under dir.
func Write(dir string, lanes []Lane, specs map[string][]string) error {
	setsDir := filepath.Join(dir, "sets")
	if err := os.RemoveAll(setsDir); err != nil {
		return err
	}
	for name, list := range specs {
		path := filepath.Join(setsDir, filepath.FromSlash(name)+".txt")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		var body string
		if len(list) > 0 {
			body = strings.Join(list, "\n") + "\n"
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
	}

	var index strings.Builder
	index.WriteString("# Generated by `make gen-test-set`. Do not edit.\n")
	index.WriteString("# ci file | lane | test set | specs\n")
	for _, l := range lanes {
		set, count := "("+l.TestType+")", "-"
		if l.RunsE2EBinary() {
			name, err := SetName(l)
			if err != nil {
				return err
			}
			set, count = name, fmt.Sprint(len(specs[name]))
		}
		fmt.Fprintf(&index, "%s | %s | %s | %s\n", l.Source, l.Name, set, count)
	}
	return os.WriteFile(filepath.Join(dir, "index.txt"), []byte(index.String()), 0o644)
}
