// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
)

// BGPFilterRuleV6ApplyConfiguration represents a declarative configuration of the BGPFilterRuleV6 type for use
// with apply.
//
// BGPFilterRuleV6 defines a BGP filter rule consisting a single IPv6 CIDR block and a filter action for this CIDR.
type BGPFilterRuleV6ApplyConfiguration struct {
	CIDR          *string                                    `json:"cidr,omitempty"`
	PrefixLength  *BGPFilterPrefixLengthV6ApplyConfiguration `json:"prefixLength,omitempty"`
	Source        *projectcalicov3.BGPFilterMatchSource      `json:"source,omitempty"`
	Interface     *string                                    `json:"interface,omitempty"`
	MatchOperator *projectcalicov3.BGPFilterMatchOperator    `json:"matchOperator,omitempty"`
	Action        *projectcalicov3.BGPFilterAction           `json:"action,omitempty"`
}

// BGPFilterRuleV6ApplyConfiguration constructs a declarative configuration of the BGPFilterRuleV6 type for use with
// apply.
func BGPFilterRuleV6() *BGPFilterRuleV6ApplyConfiguration {
	return &BGPFilterRuleV6ApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithCIDR(value string) *BGPFilterRuleV6ApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithPrefixLength sets the PrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixLength field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithPrefixLength(value *BGPFilterPrefixLengthV6ApplyConfiguration) *BGPFilterRuleV6ApplyConfiguration {
	b.PrefixLength = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithSource(value projectcalicov3.BGPFilterMatchSource) *BGPFilterRuleV6ApplyConfiguration {
	b.Source = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithInterface(value string) *BGPFilterRuleV6ApplyConfiguration {
	b.Interface = &value
	return b
}

// WithMatchOperator sets the MatchOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchOperator field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithMatchOperator(value projectcalicov3.BGPFilterMatchOperator) *BGPFilterRuleV6ApplyConfiguration {
	b.MatchOperator = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *BGPFilterRuleV6ApplyConfiguration) WithAction(value projectcalicov3.BGPFilterAction) *BGPFilterRuleV6ApplyConfiguration {
	b.Action = &value
	return b
}
