// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
)

// BGPFilterRuleV4ApplyConfiguration represents a declarative configuration of the BGPFilterRuleV4 type for use
// with apply.
//
// BGPFilterRuleV4 defines a BGP filter rule consisting a single IPv4 CIDR block and a filter action for this CIDR.
type BGPFilterRuleV4ApplyConfiguration struct {
	CIDR          *string                                    `json:"cidr,omitempty"`
	PrefixLength  *BGPFilterPrefixLengthV4ApplyConfiguration `json:"prefixLength,omitempty"`
	Source        *projectcalicov3.BGPFilterMatchSource      `json:"source,omitempty"`
	Interface     *string                                    `json:"interface,omitempty"`
	MatchOperator *projectcalicov3.BGPFilterMatchOperator    `json:"matchOperator,omitempty"`
	Action        *projectcalicov3.BGPFilterAction           `json:"action,omitempty"`
}

// BGPFilterRuleV4ApplyConfiguration constructs a declarative configuration of the BGPFilterRuleV4 type for use with
// apply.
func BGPFilterRuleV4() *BGPFilterRuleV4ApplyConfiguration {
	return &BGPFilterRuleV4ApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithCIDR(value string) *BGPFilterRuleV4ApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithPrefixLength sets the PrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixLength field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithPrefixLength(value *BGPFilterPrefixLengthV4ApplyConfiguration) *BGPFilterRuleV4ApplyConfiguration {
	b.PrefixLength = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithSource(value projectcalicov3.BGPFilterMatchSource) *BGPFilterRuleV4ApplyConfiguration {
	b.Source = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithInterface(value string) *BGPFilterRuleV4ApplyConfiguration {
	b.Interface = &value
	return b
}

// WithMatchOperator sets the MatchOperator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchOperator field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithMatchOperator(value projectcalicov3.BGPFilterMatchOperator) *BGPFilterRuleV4ApplyConfiguration {
	b.MatchOperator = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *BGPFilterRuleV4ApplyConfiguration) WithAction(value projectcalicov3.BGPFilterAction) *BGPFilterRuleV4ApplyConfiguration {
	b.Action = &value
	return b
}
