#!/bin/ash

# Copyright (c) 2017 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This wrapper script  runs the calico-felix binary and restarts it if it
# exits for a config change, which is signalled by an exit code of 129,
# as used by SIGHUP.

# Pass signals sent to this script through to Felix.
trap 'echo "SIGINT received, passing on to calico-felix"; kill -INT $pid' SIGINT
trap 'echo "SIGTERM received, passing on to calico-felix"; kill -TERM $pid' SIGTERM
trap 'echo "SIGHUP received, passing on to calico-felix"; kill -HUP $pid' SIGHUP

rc=unknown

while true; do
  echo "Starting calico-felix"
  calico-felix &
  pid=$!
  echo "Started calico-felix, PID=$pid"
  wait $pid
  rc=$?
  echo "Process stopped, RC=$rc"
  if [ "$rc" == "129" ]; then
    echo "Restarting calico-felix for config reload"
    continue
  fi
  echo "Exiting due to non-config shutdown RC=$rc"
  break
done