# Copyright (c) 2023 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FIXME: Use WINDOWS_HPC_VERSION and image instead of nanoserver and WINDOWS_VERSIONS when containerd v1.6 is EOL'd
# ARG WINDOWS_HPC_VERSION
ARG WINDOWS_VERSION

# FROM mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:${WINDOWS_HPC_VERSION}
FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

ARG GIT_VERSION=unknown

LABEL name="Calico Networking for CNI"
LABEL vendor="Project Calico"
LABEL version=${GIT_VERSION}
LABEL release="1"
LABEL summary="Calico Networking for CNI"
LABEL description="Calico Networking for CNI includes a CNI networking plugin and CNI IPAM plugin"
LABEL maintainer="maintainers@tigera.io"

COPY licenses /licenses/
COPY LICENSE /licenses/LICENSE

COPY bin/windows /opt/cni/bin/

ENV PATH=$PATH;/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install.exe"]
