FROM scratch

COPY licenses/ /licenses
COPY LICENSE /licenses/

LABEL maintainer "maintainers@projectcalico.org"

COPY bin/arm64 /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]