ARG UBI_IMAGE

FROM ${UBI_IMAGE} as ubi

LABEL maintainer "LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)"

RUN mkdir -p /opt/cni/bin

FROM scratch

COPY licenses/ /licenses
COPY bin/s390x/ /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]
