FROM s390x/debian:9.8-slim

LABEL maintainer "LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)"

COPY licenses/ /licenses
RUN mkdir -p /opt/cni/bin

FROM scratch

ADD bin/s390x/ /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]
