FROM scratch

LABEL maintainer "maintainers@projectcalico.org"

COPY licenses/ /licenses
COPY LICENSE /licenses/

COPY bin/ppc64le /opt/cni/bin/

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/opt/cni/bin/install"]