// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package time

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/projectcalico/calico/lib/std/time"
)

// NewTimer creates a new instance of Timer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Timer {
	mock := &Timer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Timer is an autogenerated mock type for the Timer type
type Timer struct {
	mock.Mock
}

type Timer_Expecter struct {
	mock *mock.Mock
}

func (_m *Timer) EXPECT() *Timer_Expecter {
	return &Timer_Expecter{mock: &_m.Mock}
}

// Chan provides a mock function for the type Timer
func (_mock *Timer) Chan() <-chan time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chan")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// Timer_Chan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chan'
type Timer_Chan_Call struct {
	*mock.Call
}

// Chan is a helper method to define mock.On call
func (_e *Timer_Expecter) Chan() *Timer_Chan_Call {
	return &Timer_Chan_Call{Call: _e.mock.On("Chan")}
}

func (_c *Timer_Chan_Call) Run(run func()) *Timer_Chan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Timer_Chan_Call) Return(vCh <-chan time.Time) *Timer_Chan_Call {
	_c.Call.Return(vCh)
	return _c
}

func (_c *Timer_Chan_Call) RunAndReturn(run func() <-chan time.Time) *Timer_Chan_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type Timer
func (_mock *Timer) Reset(d time.Duration) bool {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Duration) bool); ok {
		r0 = returnFunc(d)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Timer_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type Timer_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - d time.Duration
func (_e *Timer_Expecter) Reset(d interface{}) *Timer_Reset_Call {
	return &Timer_Reset_Call{Call: _e.mock.On("Reset", d)}
}

func (_c *Timer_Reset_Call) Run(run func(d time.Duration)) *Timer_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Timer_Reset_Call) Return(b bool) *Timer_Reset_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Timer_Reset_Call) RunAndReturn(run func(d time.Duration) bool) *Timer_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Timer
func (_mock *Timer) Stop() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Timer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Timer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Timer_Expecter) Stop() *Timer_Stop_Call {
	return &Timer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Timer_Stop_Call) Run(run func()) *Timer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Timer_Stop_Call) Return(b bool) *Timer_Stop_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Timer_Stop_Call) RunAndReturn(run func() bool) *Timer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
