{
 "title": "Felix Dashboard (Calico)",
 "description": "Felix dashboard is part of calico documentation website, you will have great insight about you Calico instance by using this dashboard.",
 "tags": [
  "calico",
  "felix",
  "kubernetes",
  "k8s",
  "calico-node",
  "cloud",
  "cluster monitoring",
  "policy monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "storage_name", "label": "Storage Name", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Alerts and general info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active hosts on each node",
   "type": "gauge",
   "description": "These metrics are part of general information related to your Calico implementation.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "iptables save errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ipset errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_ipset_errors[5m]))"
    }
   ]
  },
  {
   "title": "Active calico nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(felix_cluster_num_hosts)", "legendFormat": "Calico node" }
   ]
  },
  {
   "title": "Errors plot",
   "type": "timeseries",
   "description": "This graph shows you all the errors that Calico encounters, it is important to note occasional errors are acceptable. However, rise in the number of error or constant error counters means Calico is not working properly.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(felix_ipset_errors[5m])", "legendFormat": "{{instance}} ipset errors" },
    {
     "expr": "rate(felix_iptables_restore_errors[5m])",
     "legendFormat": "{{instance}} iptables restore errors"
    },
    {
     "expr": "rate(felix_iptables_save_errors[5m])",
     "legendFormat": "{{instance}} iptables save errors"
    },
    { "expr": "rate(felix_log_errors[5m])", "legendFormat": "{{instance}} log errors" }
   ]
  },
  {
   "title": "Felix cluster policies",
   "type": "gauge",
   "description": "More policies on Felix means more effort required by Calico to manage packets. ",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "felix_cluster_num_policies", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "iptables restore errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_restore_errors[5m]))"
    }
   ]
  },
  {
   "title": "Felix log errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_log_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix resync started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_resyncs_started[5m])) "
    }
   ]
  },
  {
   "title": "Felix dropped logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "felix_logs_dropped", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dataplane apply time quantile 0.5",
   "type": "timeseries",
   "description": "Dataplane apply time can indicate how busy your Kubernetes instance is. This can slow down Calico performance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Route table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Felix route table list seconds quantile 0.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix route table list seconds quantile 0.9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix route table list seconds quantile 0.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "felix_route_table_list_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Calico Typha",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "storage_name", "label": "Storage Name", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Top-level metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datastore cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_cache_size)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"typha_metrics\"}[30s]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"typha_metrics\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total connections accepted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typha_connections_accepted[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client connections actively streaming",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (typha_connections_streaming)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rebalanced client connenctions",
   "type": "timeseries",
   "description": "Number of client connections dropped to rebalance load.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(typha_connections_dropped[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99%ile Client fall-behind",
   "type": "timeseries",
   "description": "This metric measures how far behind Typha's clients are at reading updates.\nIt goes up if the client is slow or if Typha is overloaded and it cannot keep up with writes to all its clients.\nIt is normal for this to spike when new clients connect, they must download and process the snapshot, during which time they get slightly behind.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_client_latency_secs{quantile='0.99'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99%ile write latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_client_write_latency_secs)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99%ile client ping latency",
   "type": "timeseries",
   "description": "This metric tracks how long it takes for Typha's clients to respond to pings over the Typha protocol.\nAn increase in this metric indicates that the clients, network or Typha are more heavily loaded.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_ping_latency{quantile=\"0.99\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cache internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "99%ile Breadcrumb Size",
   "type": "timeseries",
   "description": "Internally, Typha stores datastore changes as a series of blocks called breadcrumbs.\nThe default maximum size of a block is 100 so, if Typha is consistently generating size-100 blocks it may be overloaded.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_breadcrumb_size{quantile=\"0.99\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Non-blocking breadcrumb fraction",
   "type": "timeseries",
   "description": "Internally, Typha stores datastore changes as a series of blocks called \"breadcrumbs\".\nEach client \"follows the breadcrumbs\" either by blocking and waiting or skipping straight to the next one (non-blocking) if it is already available.\nAs load on Typha increases, the ratio of skip ahead non-blocking reads increases.  If it approaches 100% then Typha may be overloaded (since clients only do non-blocking reads when they're behind).",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance) (rate(typha_breadcrumb_non_block[30s])))/((sum by (instance) (rate(typha_breadcrumb_non_block[30s])))+(sum by (instance) (rate(typha_breadcrumb_block[30s]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Datastore updates total",
   "type": "timeseries",
   "description": "This panel shows the rate of updates from the datastore(s).\nFor example, updates to Pods/Nodes/Policies/etc.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(typha_updates_total[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Datastore updates skipped as no-ops",
   "type": "timeseries",
   "description": "This panel shows the number of updates from the datastore that Typha detected were no-ops.\nFor example, an update to a Kubernetes Node resource that didn't touch any values that Calico cares about.\nSuch updates are not propagated to clients, saving resources.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(typha_updates_skipped[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Snapshot details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Median snapshot send time",
   "type": "timeseries",
   "description": "This panel shows the 99%ile time to stream the initial datastore snapshot to each clients.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (typha_client_snapshot_send_secs{quantile=\"0.5\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients requiring grace period",
   "type": "timeseries",
   "description": "After sending the snapshot to the client, Typha allows a grace period for the client to catch up to the most recent data.\nThis metric tracks how many clients required the grace period.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (typha_connections_grace_used)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max snapshot size (raw)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(typha_snapshot_raw_bytes)" }
   ]
  },
  {
   "title": "Max snapshot size (compressed)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(typha_snapshot_compressed_bytes)"
    }
   ]
  }
 ]
}