// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	projectcalicov3 "github.com/projectcalico/api/pkg/client/applyconfiguration_generated/projectcalico/v3"
	typedprojectcalicov3 "github.com/projectcalico/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAMBlocks implements IPAMBlockInterface
type fakeIPAMBlocks struct {
	*gentype.FakeClientWithListAndApply[*v3.IPAMBlock, *v3.IPAMBlockList, *projectcalicov3.IPAMBlockApplyConfiguration]
	Fake *FakeProjectcalicoV3
}

func newFakeIPAMBlocks(fake *FakeProjectcalicoV3) typedprojectcalicov3.IPAMBlockInterface {
	return &fakeIPAMBlocks{
		gentype.NewFakeClientWithListAndApply[*v3.IPAMBlock, *v3.IPAMBlockList, *projectcalicov3.IPAMBlockApplyConfiguration](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("ipamblocks"),
			v3.SchemeGroupVersion.WithKind("IPAMBlock"),
			func() *v3.IPAMBlock { return &v3.IPAMBlock{} },
			func() *v3.IPAMBlockList { return &v3.IPAMBlockList{} },
			func(dst, src *v3.IPAMBlockList) { dst.ListMeta = src.ListMeta },
			func(list *v3.IPAMBlockList) []*v3.IPAMBlock { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.IPAMBlockList, items []*v3.IPAMBlock) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
