// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	projectcalicov3 "github.com/projectcalico/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeCalicoNodeStatuses implements CalicoNodeStatusInterface
type fakeCalicoNodeStatuses struct {
	*gentype.FakeClientWithList[*v3.CalicoNodeStatus, *v3.CalicoNodeStatusList]
	Fake *FakeProjectcalicoV3
}

func newFakeCalicoNodeStatuses(fake *FakeProjectcalicoV3) projectcalicov3.CalicoNodeStatusInterface {
	return &fakeCalicoNodeStatuses{
		gentype.NewFakeClientWithList[*v3.CalicoNodeStatus, *v3.CalicoNodeStatusList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("caliconodestatuses"),
			v3.SchemeGroupVersion.WithKind("CalicoNodeStatus"),
			func() *v3.CalicoNodeStatus { return &v3.CalicoNodeStatus{} },
			func() *v3.CalicoNodeStatusList { return &v3.CalicoNodeStatusList{} },
			func(dst, src *v3.CalicoNodeStatusList) { dst.ListMeta = src.ListMeta },
			func(list *v3.CalicoNodeStatusList) []*v3.CalicoNodeStatus { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.CalicoNodeStatusList, items []*v3.CalicoNodeStatus) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
