#!/usr/bin/env bash
# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is run locally to push artifacts to our sub-directory in GCS.
# The counterpart to this script is load-test-artifacts, which runs on the test
# VM.  It can assume that the artifacts have been downloaded to /tmp.

set -e
set -x

cd ../..

# Copy pre-built images from the workflow cache if available.
# These were built by the "Build: *" blocks in the Prerequisites stage.
for img in calico-image.tar.zst node-image.tar.zst whisker-image.tar.zst; do
  if gcloud storage cp "${GCS_WORKFLOW_DIR}/${img}" "/tmp/${img}" 2>/dev/null; then
    echo "Found pre-built ${img}, including in artifacts."
    gcloud storage cp "/tmp/${img}" "${GCS_WORKFLOW_DIR}/node/fv-artifacts/${img}"
  fi
done

tar -czf /tmp/working-copy.tgz \
  --exclude=${CALICO_DIR_NAME}/artifacts \
  ${CALICO_DIR_NAME}
gcloud storage cp /tmp/working-copy.tgz "${GCS_WORKFLOW_DIR}/node/fv-artifacts/"
