#!/bin/sh
exec 2>&1
GUNICORN=/usr/local/bin/gunicorn
ROOT=/
PID=/var/run/gunicorn.pid
APP=calico_containers.docker_plugin:app

if [ -f $PID ]; then rm $PID; fi

exec $GUNICORN --chdir $ROOT --pid=$PID \
-b unix:///usr/share/docker/plugins/calico.sock $APP \
--access-logfile -