#!/bin/sh
exec 2>&1

if [ "$DATASTORE_TYPE" = "kubernetes" ]
then
    exec confd -confdir=/etc/calico/confd -interval=5 -log-level=debug -backend=k8s
else
    ETCD_NODE=${ETCD_ENDPOINTS:=${ETCD_SCHEME:=http}://${ETCD_AUTHORITY}}
    ETCD_ENDPOINTS_CONFD=`echo "-node=$ETCD_NODE" | sed -e 's/,/ -node=/g'`

    exec confd -confdir=/etc/calico/confd -interval=5 -watch --log-level=debug \
           $ETCD_ENDPOINTS_CONFD -client-key=${ETCD_KEY_FILE} \
           -client-cert=${ETCD_CERT_FILE} -client-ca-keys=${ETCD_CA_CERT_FILE}
fi
