#!/bin/bash -ex

# Copyright (c) 2018 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

: ${FV_NUM_BATCHES:=4}
: ${FV_BATCHES_TO_RUN:=1 2 3 4}
: ${FV_SLOW_SPEC_THRESH:=90}
: ${GINKGO_ARGS:=}

for batch in ${FV_BATCHES_TO_RUN}; do
  (
     echo "Running FV batch ${batch}"
     ./fv.test -ginkgo.parallel.node ${batch} \
               -ginkgo.parallel.total ${FV_NUM_BATCHES} \
               -ginkgo.seed 1 \
               -ginkgo.randomizeAllSpecs=true \
               -ginkgo.slowSpecThreshold ${FV_SLOW_SPEC_THRESH} \
               ${GINKGO_ARGS}; \
  ) &
  pids[${batch}]=$!
done

for batch in ${FV_BATCHES_TO_RUN}; do
  echo "Waiting on batch $batch; PID=${pids[$batch]}"
  wait ${pids[$batch]}
  echo "Result: $?"
done
