#!/bin/bash
LOGDIR=/var/log/calico/bird
mkdir -p $LOGDIR
touch $LOGDIR/config
echo "s10000000" >> $LOGDIR/config
echo "n5" >> $LOGDIR/config
# Prefix each line with a timestamp
tee >(svlogd -ttt $LOGDIR)