{{- if .Values.includeCRDs -}}
{{- if .Values.useV3CRDs -}}
{{ range $path, $_ := .Files.Glob "crds-v3/*" }}
{{ $.Files.Get $path }}
---
{{- end -}}
{{- else -}}
{{ range $path, $_ := .Files.Glob "crds/*" }}
{{ $.Files.Get $path }}
---
{{- end -}}
{{- end -}}
{{- end -}}
