#!/usr/bin/env bash

# shellcheck disable=SC1091

set -x      # Print commands as they're run
set -e      # Exit immediately if a command returns non-zero

apt-get -q update
DEBIAN_FRONTEND=noninteractive \
apt-get install -y -q build-essential  \
                   devscripts \
                   debhelper \
                   dh-python \
                   python-all \
                   python-setuptools \
                   python3-all \
                   python3-setuptools \
                   libyajl2 \
                   libdatrie1 \
                   git \
                   libnetfilter-conntrack-dev \
                   libidn11-dev \
                   libdbus-1-dev \
                   libgmp-dev \
                   nettle-dev \
                   m4 \
                   texinfo
apt-get clean -y
