FROM golang:1.7
MAINTAINER Tom Denham <tom@tigera.io>

# These are only required for running the tests in a container.
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega

WORKDIR /go/src/github.com/projectcalico/calicoctl
