FROM s390x/golang:1.8.3
MAINTAINER LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)

# These are only required for running the tests in a container.
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega

WORKDIR /go/src/github.com/projectcalico/calicoctl
