FROM ppc64le/alpine:3.10
MAINTAINER Tom Denham <tom@projectcalico.org>

RUN apk --no-cache upgrade apk-tools

ADD bin/calicoctl-linux-ppc64le /calicoctl

ENV CALICO_CTL_CONTAINER=TRUE
ENV PATH=$PATH:/

WORKDIR /root
ENTRYPOINT ["/calicoctl"]
