#!/usr/bin/env bash

set -x
set -e

if [ -z "${DEB_VERSION}" ]; then
  echo "DEB_VERSION variable should be set"
  exit 1
fi
if [ -z "${STREAM}" ]; then
  echo "STREAM variable should be set to trusty/xenial/..."
  exit 1
fi

deb_dir=dist/$STREAM
unpacked_src_dir=${deb_dir}/calico-${DEB_VERSION}

rm -rf ${deb_dir}
mkdir -p ${unpacked_src_dir}/bin
cp bin/calico-felix ${unpacked_src_dir}/bin
cp etc/calico-diags ${unpacked_src_dir}/bin
cp etc/*.sh ${unpacked_src_dir}/bin
cp -r etc \
      LICENSE \
      README.md \
      ${unpacked_src_dir}

cp -r debian ${unpacked_src_dir}

head -n 1 "${unpacked_src_dir}/debian/changelog" | grep -q "__STREAM__" || exit 1
sed -i "s/__STREAM__/${STREAM}/g" "${unpacked_src_dir}/debian/changelog"

cd ${unpacked_src_dir}

debuild --no-lintian -i="" $excludes -us -uc -b
debuild --no-lintian --no-tgz-check -i="" $excludes -us -uc -S

set +x
echo
echo "Build complete.  Source and binary debs now in ${deb_dir}."
