#!/usr/bin/env bash
# Copyright (c) 2023 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

vm_prefix=$1
if [ -z "$vm_prefix" ]; then
  echo "Usage: $0 <vm-name-prefix>"
  exit 1
fi

project=${GCP_PROJECT:-unique-caldron-775}
gcp_secret_key=${GCP_SECRET_KEY:-$HOME/secrets/secret.google-service-account-key.json}

gcloud config set project $project
gcloud auth activate-service-account --key-file=$gcp_secret_key

while true; do
  gcloud --quiet compute instances list \
        "--filter=name~'${vm_prefix}.*'" \
        --zones=${ZONE} \
        --format='table[no-heading](name)' > instance-list
  instances="$(cat instance-list)"
  if [ "${instances}" = "" ]; then
    echo "All instances deleted"
    break
  fi
  echo "Instances to delete: $instances"
  gcloud --quiet beta compute instances delete ${instances} --zone=${ZONE} --no-graceful-shutdown
  sleep 1
done
