#!/usr/bin/env bash

# Copyright (c) 2019 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

my_dir="$(dirname $0)"
vm_name=$1
project=unique-caldron-775
zone=${ZONE:-europe-west3-c}
disk_size=${VM_DISK_SIZE:-20GB}
project=${GCP_PROJECT:-unique-caldron-775}
gcp_secret_key=${GCP_SECRET_KEY:-$HOME/secrets/secret.google-service-account-key.json}

# Note: these all get overridden in the fv-preamble script.
: "${IMAGE:=ubuntu-2204-jammy-v20250312}"
: "${DOCKER_VERSION=5:20.10.14~3-0~ubuntu-jammy}"
: "${UBUNTU_VERSION=jammy}"
: "${SKIP_FIRST_CREATE=false}"
: "${MAX_RUN_DURATION:=4h}"

gcloud config set project $project
gcloud auth activate-service-account --key-file=$gcp_secret_key

function create-vm() {
  if [ "$SKIP_FIRST_CREATE" = "true" ] ; then
    SKIP_FIRST_CREATE=false
  else
    gcloud --quiet compute instances create "${vm_name}" \
             --zone=${zone} \
             --machine-type=n4-standard-4 \
             --image=${IMAGE} \
             --image-project=ubuntu-os-cloud \
             --boot-disk-size=$disk_size \
             --boot-disk-type=hyperdisk-balanced \
             --max-run-duration="${MAX_RUN_DURATION}" \
             --instance-termination-action=DELETE \
             --metadata-from-file startup-script="$my_dir/vm-bootstrap.sh" \
             --metadata block-project-ssh-keys=TRUE,ssh-keys="ubuntu:$(ssh-keygen -y -f $HOME/.ssh/id_rsa)",enable-guest-attributes=TRUE
  fi && \

  local vm_ip
  local vm_pub_key
  vm_pub_key=""
  while [ -z "$vm_pub_key" ]; do
    echo "Waiting for VM SSH host key..."
    sleep 2
    vm_pub_key=$(gcloud compute instances get-guest-attributes ${vm_name} --zone=${zone} --query-path="hostkeys/ssh-ed25519" --format='value(value)')
    echo "VM SSH host key: $vm_pub_key"
  done
  vm_ip=$(gcloud compute instances describe ${vm_name} --zone=${zone} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
  echo "$vm_ip ssh-ed25519 $vm_pub_key" >> ~/.ssh/known_hosts

  ssh_cmd="ssh ubuntu@${vm_ip}"

  for ssh_try in $(seq 1 10); do
    echo "Trying to SSH in: $ssh_try"
    ${ssh_cmd} -- echo "Success" && break
    sleep 1
  done  && \
  for ssh_try in $(seq 1 100); do
    echo "Checking startup script completion: $ssh_try"
    ${ssh_cmd} -- test -e /var/run/startup-script-complete && break
    sleep 1
  done  && \
  set +x && \
  echo "$DOCKERHUB_PASSWORD" | gcloud --quiet compute ssh --zone=${zone} "ubuntu@${vm_name}" -- docker login --username "$DOCKERHUB_USERNAME" --password-stdin && \
  set -x && \
  scp -r -C "$HOME/secrets" "ubuntu@${vm_ip}:/home/ubuntu/secrets" && \
  ${ssh_cmd} -- gcloud config set project unique-caldron-775 && \
  ${ssh_cmd} -- gcloud auth activate-service-account --key-file=/home/ubuntu/secrets/secret.google-service-account-key.json && \
  ${ssh_cmd} -- gcloud storage cp "${GCS_TRANSIENT_DIR_URL}/*" /tmp && \
  ${ssh_cmd} -- tar -xzf /tmp/working-copy.tgz && \
  ${ssh_cmd} -- docker load -i /tmp/calico-felix-test.tar && \
  ${ssh_cmd} -- docker load -i /tmp/felixtest-typha.tar && \
  ${ssh_cmd} -- docker tag calico/felix-test:latest-amd64 felix-test:latest-amd64
}

function delete-vm() {
  gcloud --quiet compute instances delete "${vm_name}" --zone=${zone}
}

for attempt in $(seq 1 5); do
  echo "Trying to create test VM, attempt ${attempt}"
  if create-vm; then
    echo "Success!"
    exit 0
  else
    echo "Failed to create VM.  Tearing it down."
    delete-vm || true
  fi
done

echo "Out of retries"
exit 1
