#!/bin/bash

set -e
set -x

job_tag="$1"

my_dir="$(dirname $0)"
repo_dir="$my_dir/../.."
artifacts_dir="${repo_dir}/artifacts"

echo "Publishing any reports from the artifacts directory."

cd "$artifacts_dir"

if [ "$COMPONENT" = "felix" ]; then
  # The UTs get lost amongst the FVs, so split them into separate reports.
  mapfile -t report_names < <(find . -name '*.xml' | grep '_fv_')
  echo "FV reports:" "${report_names[@]}"
  json_files=()
  if [ ${#report_names[@]} -ne 0 ]; then
    test-results compile --name "$job_tag: FV" "${report_names[@]}" fv_report.json
    json_files+=(fv_report.json)
  fi
  mapfile -t report_names < <(find . -name '*.xml' | grep -v '_fv_')
  echo "UT reports:" "${report_names[@]}"
  if [ ${#report_names[@]} -ne 0 ]; then
    test-results compile --name "$job_tag: UT" "${report_names[@]}" ut_report.json
    json_files+=(ut_report.json)
  fi
  if [ ${#json_files[@]} -ne 0 ]; then
    # Simulate test-results publish.
    test-results combine "${json_files[@]}" report.json
    artifact push job report.json -d test-results/junit.json || true
    artifact push workflow report.json -d test-results/${SEMAPHORE_PIPELINE_ID}/${SEMAPHORE_JOB_ID}.json || true
  fi
else
  find . -name '*.xml' -print0 | xargs -r -0 test-results publish --name "$job_tag"
fi