#!/usr/bin/env bash
# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

my_dir="$(dirname "$0")"
repo_dir="$my_dir/../.."

# COMPONENT might be node or felix; give shellcheck something to work with.
# shellcheck source=../../felix/.semaphore/batches.sh
source "${repo_dir}/${COMPONENT}/.semaphore/batches.sh"

vm_name_prefix=$1
shift 1

echo
echo "===== Starting tests ====="
echo

for batch in "${batches[@]}"; do
  vm_name="$vm_name_prefix$batch"
  VM_NAME="$vm_name" "$my_dir/on-test-vm" "$@"
done

echo "===== Done ====="
