#!/usr/bin/env bash
# Copyright (c) 2023-2026 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ -z "${VM_NAME}" ]; then
  echo "VM_NAME is not set; it should be set to the name of the test VM" 1>&2
  exit 1
fi
if [ -z "${ZONE}" ]; then
  echo "ZONE is not set; it should be set to the GCP zone of the test VM" 1>&2
  exit 1
fi

ip_cache_file="/tmp/vm_ip_${VM_NAME}_${ZONE}"
if [ -e "$ip_cache_file" ]; then
  vm_ip=$(cat "$ip_cache_file")
else
  vm_ip=$(gcloud compute instances describe "${VM_NAME}" --zone="${ZONE}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
  echo "$vm_ip" > "$ip_cache_file"
fi
echo "$vm_ip"
