// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewSession creates a new instance of Session. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *Session {
	mock := &Session{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

type Session_Expecter struct {
	mock *mock.Mock
}

func (_m *Session) EXPECT() *Session_Expecter {
	return &Session_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type Session
func (_mock *Session) Accept() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Session_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type Session_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
func (_e *Session_Expecter) Accept() *Session_Accept_Call {
	return &Session_Accept_Call{Call: _e.mock.On("Accept")}
}

func (_c *Session_Accept_Call) Run(run func()) *Session_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Accept_Call) Return(conn net.Conn, err error) *Session_Accept_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *Session_Accept_Call) RunAndReturn(run func() (net.Conn, error)) *Session_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Addr provides a mock function for the type Session
func (_mock *Session) Addr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// Session_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type Session_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *Session_Expecter) Addr() *Session_Addr_Call {
	return &Session_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *Session_Addr_Call) Run(run func()) *Session_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Addr_Call) Return(addr net.Addr) *Session_Addr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *Session_Addr_Call) RunAndReturn(run func() net.Addr) *Session_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Session
func (_mock *Session) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Session_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Session_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Session_Expecter) Close() *Session_Close_Call {
	return &Session_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Session_Close_Call) Run(run func()) *Session_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Close_Call) Return(err error) *Session_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Session_Close_Call) RunAndReturn(run func() error) *Session_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type Session
func (_mock *Session) Open() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Session_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type Session_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
func (_e *Session_Expecter) Open() *Session_Open_Call {
	return &Session_Open_Call{Call: _e.mock.On("Open")}
}

func (_c *Session_Open_Call) Run(run func()) *Session_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Session_Open_Call) Return(conn net.Conn, err error) *Session_Open_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *Session_Open_Call) RunAndReturn(run func() (net.Conn, error)) *Session_Open_Call {
	_c.Call.Return(run)
	return _c
}
