#!/usr/bin/env bash
set -x
set -e

apt-get update
apt-get install -y build-essential  \
                   devscripts \
                   debhelper \
                   dh-systemd \
                   python-all \
                   python-setuptools \
                   libyajl2 \
                   libdatrie1 \
                   python-pbr \
                   git \
                   libnetfilter-conntrack-dev \
		   libidn11-dev \
		   libdbus-1-dev \
		   libgmp-dev \
		   nettle-dev \
		   m4 \
		   texinfo
apt-get clean -y
