#!/usr/bin/env bash
# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is run locally to push artifacts to our sub-directory in GCS.
# The counterpart to this script is load-test-artifacts, which runs on the test
# VM.  It can assume that the artifacts have been downloaded to /tmp.

set -e
set -x

artifact push job bin &
docker save -o /tmp/calico-felix-test.tar calico/felix-test:latest-amd64

# The combined calico image (which provides Typha and other components used by
# the FVs) is already published to ${GCS_WORKFLOW_DIR}/calico-image.tar.zst by
# the "Build: calico image" prerequisite block. Server-side copy it into this
# component's fv-artifacts directory so the test VM sees it alongside the
# working copy and felix-test image.
gcloud storage cp "${GCS_WORKFLOW_DIR}/calico-image.tar.zst" "${GCS_WORKFLOW_DIR}/felix/fv-artifacts/calico-image.tar.zst"

cd ../..

# Future work: Split UT and FV artifacts so we can be even more selective.
# Excluding Typha binaries because we only need the image.
tar -czf /tmp/working-copy.tgz \
  --exclude=${CALICO_DIR_NAME}/.go-pkg-cache \
  --exclude=${CALICO_DIR_NAME}/typha/bin \
  --exclude=${CALICO_DIR_NAME}/typha/docker-image/bin \
  --exclude=${CALICO_DIR_NAME}/artifacts \
  ${CALICO_DIR_NAME}
gcloud storage cp /tmp/working-copy.tgz /tmp/calico-felix-test.tar "${GCS_WORKFLOW_DIR}/felix/fv-artifacts/"
wait
