#!/usr/bin/env bash
# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is run locally to push the FV test artifacts to our sub-directory
# in GCS. The counterpart to this script is load-test-artifacts, which runs on
# the test VM.  It can assume that the artifacts have been downloaded to /tmp.
#
# fv-artifacts are published to GCS (GCS_WORKFLOW_DIR) rather than the S3 build
# cache so the in-cloud GCP test VMs fetch them without cross-cloud egress. The
# source calico image, however, lives on S3 (S3_WORKFLOW_DIR), published there
# by the "Build: calico image" prerequisite block, so this script bridges the
# two backends: `s3-cmd` (S3) to fetch, `gcloud storage` (GCS) to publish.

set -e
set -x

# Resolve the s3-cmd wrapper before we cd out of the component directory.
S3_CMD="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/.semaphore/s3-cmd"

artifact push job bin &
docker save -o /tmp/calico-felix-test.tar calico/felix-test:latest-amd64

# The combined calico image (which provides Typha and other components used by
# the FVs) is published to ${S3_WORKFLOW_DIR}/calico-image.tar.zst on S3 by the
# "Build: calico image" prerequisite block. Fetch it from S3 and re-upload it
# into this component's GCS fv-artifacts directory so the test VM sees it
# alongside the working copy and felix-test image.
"$S3_CMD" cp "${S3_WORKFLOW_DIR}/calico-image.tar.zst" /tmp/calico-image.tar.zst
gcloud storage cp /tmp/calico-image.tar.zst "${GCS_WORKFLOW_DIR}/felix/fv-artifacts/calico-image.tar.zst"

cd ../..

# Future work: Split UT and FV artifacts so we can be even more selective.
# Excluding Typha binaries because we only need the image.
tar -czf /tmp/working-copy.tgz \
  --exclude=${CALICO_DIR_NAME}/.go-pkg-cache \
  --exclude=${CALICO_DIR_NAME}/typha/bin \
  --exclude=${CALICO_DIR_NAME}/typha/docker-image/bin \
  --exclude=${CALICO_DIR_NAME}/artifacts \
  ${CALICO_DIR_NAME}
gcloud storage cp /tmp/working-copy.tgz /tmp/calico-felix-test.tar "${GCS_WORKFLOW_DIR}/felix/fv-artifacts/"
wait
