#!/usr/bin/env bash

# Copyright (c) 2019 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
set -x

vm_prefix=$1
project=unique-caldron-775
zone=europe-west3-c

gcloud config set project $project
gcloud auth activate-service-account --key-file=$HOME/secrets/secret.google-service-account-key.json

while true; do
  gcloud --quiet compute instances list \
        "--filter=name~'${vm_prefix}.*'" \
        --zones=${zone} \
        --format='table[no-heading](name)' > instance-list
  instances="$(cat instance-list)"
  if [ "${instances}" = "" ]; then
    echo "All instances deleted"
    break
  fi
  echo "Instances to delete: $instances"
  gcloud --quiet compute instances delete ${instances} --zone=${zone}
  sleep 1
done 
