// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/projectcalico/calico/goldmane/proto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewFlowsStreamClient creates a new instance of FlowsStreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowsStreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowsStreamClient {
	mock := &FlowsStreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FlowsStreamClient is an autogenerated mock type for the FlowsStreamClient type
type FlowsStreamClient struct {
	mock.Mock
}

type FlowsStreamClient_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowsStreamClient) EXPECT() *FlowsStreamClient_Expecter {
	return &FlowsStreamClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FlowsStreamClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type FlowsStreamClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *FlowsStreamClient_Expecter) CloseSend() *FlowsStreamClient_CloseSend_Call {
	return &FlowsStreamClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *FlowsStreamClient_CloseSend_Call) Run(run func()) *FlowsStreamClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlowsStreamClient_CloseSend_Call) Return(err error) *FlowsStreamClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FlowsStreamClient_CloseSend_Call) RunAndReturn(run func() error) *FlowsStreamClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// FlowsStreamClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type FlowsStreamClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *FlowsStreamClient_Expecter) Context() *FlowsStreamClient_Context_Call {
	return &FlowsStreamClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *FlowsStreamClient_Context_Call) Run(run func()) *FlowsStreamClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlowsStreamClient_Context_Call) Return(context1 context.Context) *FlowsStreamClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *FlowsStreamClient_Context_Call) RunAndReturn(run func() context.Context) *FlowsStreamClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowsStreamClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type FlowsStreamClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *FlowsStreamClient_Expecter) Header() *FlowsStreamClient_Header_Call {
	return &FlowsStreamClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *FlowsStreamClient_Header_Call) Run(run func()) *FlowsStreamClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlowsStreamClient_Header_Call) Return(mD metadata.MD, err error) *FlowsStreamClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *FlowsStreamClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *FlowsStreamClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) Recv() (*proto.FlowResult, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *proto.FlowResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*proto.FlowResult, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *proto.FlowResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.FlowResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FlowsStreamClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type FlowsStreamClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *FlowsStreamClient_Expecter) Recv() *FlowsStreamClient_Recv_Call {
	return &FlowsStreamClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *FlowsStreamClient_Recv_Call) Run(run func()) *FlowsStreamClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlowsStreamClient_Recv_Call) Return(flowResult *proto.FlowResult, err error) *FlowsStreamClient_Recv_Call {
	_c.Call.Return(flowResult, err)
	return _c
}

func (_c *FlowsStreamClient_Recv_Call) RunAndReturn(run func() (*proto.FlowResult, error)) *FlowsStreamClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FlowsStreamClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type FlowsStreamClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *FlowsStreamClient_Expecter) RecvMsg(m interface{}) *FlowsStreamClient_RecvMsg_Call {
	return &FlowsStreamClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *FlowsStreamClient_RecvMsg_Call) Run(run func(m any)) *FlowsStreamClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FlowsStreamClient_RecvMsg_Call) Return(err error) *FlowsStreamClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FlowsStreamClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *FlowsStreamClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FlowsStreamClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type FlowsStreamClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *FlowsStreamClient_Expecter) SendMsg(m interface{}) *FlowsStreamClient_SendMsg_Call {
	return &FlowsStreamClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *FlowsStreamClient_SendMsg_Call) Run(run func(m any)) *FlowsStreamClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FlowsStreamClient_SendMsg_Call) Return(err error) *FlowsStreamClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FlowsStreamClient_SendMsg_Call) RunAndReturn(run func(m any) error) *FlowsStreamClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type FlowsStreamClient
func (_mock *FlowsStreamClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// FlowsStreamClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type FlowsStreamClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *FlowsStreamClient_Expecter) Trailer() *FlowsStreamClient_Trailer_Call {
	return &FlowsStreamClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *FlowsStreamClient_Trailer_Call) Run(run func()) *FlowsStreamClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlowsStreamClient_Trailer_Call) Return(mD metadata.MD) *FlowsStreamClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *FlowsStreamClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *FlowsStreamClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
