// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/whisker-backend/pkg/apis/v1"
)

// NewStreamingFlowsBackend creates a new instance of StreamingFlowsBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamingFlowsBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *StreamingFlowsBackend {
	mock := &StreamingFlowsBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StreamingFlowsBackend is an autogenerated mock type for the StreamingFlowsBackend type
type StreamingFlowsBackend struct {
	mock.Mock
}

// List provides a mock function for the type StreamingFlowsBackend
func (_mock *StreamingFlowsBackend) List(ctx context.Context, params v1.ListFlowsParams) (int, []v1.FlowResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 int
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int)
	}

	var r1 []v1.FlowResponse
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]v1.FlowResponse)
	}

	return r0, r1, ret.Error(2)
}

// FilterHints provides a mock function for the type StreamingFlowsBackend
func (_mock *StreamingFlowsBackend) FilterHints(ctx context.Context, params v1.FlowFilterHintsRequest, includeFlow v1.FlowFilterFunc) (int, []v1.FlowFilterHintResponse, error) {
	ret := _mock.Called(ctx, params, includeFlow)

	if len(ret) == 0 {
		panic("no return value specified for FilterHints")
	}

	var r0 int
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(int)
	}

	var r1 []v1.FlowFilterHintResponse
	if ret.Get(1) != nil {
		r1 = ret.Get(1).([]v1.FlowFilterHintResponse)
	}

	return r0, r1, ret.Error(2)
}

// Stream provides a mock function for the type StreamingFlowsBackend
func (_mock *StreamingFlowsBackend) Stream(ctx context.Context, params v1.ListFlowsParams) (v1.FlowStream, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 v1.FlowStream
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(v1.FlowStream)
	}

	return r0, ret.Error(1)
}
