# Copyright (c) 2023 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FIXME: Use WINDOWS_HPC_VERSION and image instead of nanoserver and WINDOWS_VERSIONS when containerd v1.6 is EOL'd
# ARG WINDOWS_HPC_VERSION
ARG WINDOWS_VERSION

#FROM mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:${WINDOWS_HPC_VERSION}
FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_VERSION}

ARG GIT_VERSION=unknown

# Required labels for certification
LABEL name="Calico node" \
      vendor="Project Calico" \
      version=$GIT_VERSION \
      release="1" \
      summary="Calico node handles networking and policy for Calico" \
      description="Calico node handles networking and policy for Calico" \
      maintainer="maintainers@tigera.io"

COPY LICENSE /licenses/

COPY dist/bin/calico-node.exe /CalicoWindows/calico-node.exe
COPY windows-packaging/CalicoWindows/felix/felix-service.ps1 /CalicoWindows/felix-service.ps1
COPY windows-packaging/CalicoWindows/node/node-service.ps1 /CalicoWindows/node-service.ps1
COPY windows-packaging/CalicoWindows/confd /CalicoWindows/confd
COPY windows-packaging/CalicoWindows/config-hpc.ps1 /CalicoWindows/config.ps1
COPY windows-packaging/CalicoWindows/libs/calico/calico.psm1 /CalicoWindows/libs/calico/calico.psm1
COPY windows-packaging/CalicoWindows/libs/hns/hns.psm1 /CalicoWindows/libs/hns/hns.psm1
COPY windows-packaging/nssm.exe /nssm.exe
COPY windows-packaging/CalicoWindows/uninstall-calico-hpc.ps1 /uninstall-calico.ps1

ENV PATH=$PATH;/CalicoWindows
WORKDIR /CalicoWindows
# The nanoserver image does not have powershell but this works because
# this container will be running on the host.
ENTRYPOINT ["powershell"]
