# Copyright (c) 2015-2019 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM mcr.microsoft.com/windows/nanoserver:1809

ARG GIT_VERSION=unknown

# Required labels for certification
LABEL name="Calico node" \
      vendor="Project Calico" \
      version=$GIT_VERSION \
      release="1" \
      summary="Calico node handles networking and policy for Calico" \
      description="Calico node handles networking and policy for Calico" \
      maintainer="laurence@tigera.io"

ADD LICENSE /licenses/

ADD dist/bin/calico-node.exe /calico/calico-node.exe
ADD windows-packaging/CalicoWindows/felix/felix-service.ps1 /calico/felix-service.ps1
ADD windows-packaging/CalicoWindows/node/node-service.ps1 /calico/node-service.ps1
Add windows-packaging/CalicoWindows/libs/calico/calico.psm1 /calico/libs/calico/calico.psm1
Add windows-packaging/CalicoWindows/libs/hns/hns.psm1 /calico/libs/hns/hns.psm1

ENV PATH=$PATH:/calico
ENTRYPOINT ["powershell"]
