# Copyright (c) 2025-2026 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG CALICO_BASE

FROM scratch AS source

ARG TARGETARCH

COPY bin/ztunnel-${TARGETARCH} /usr/bin/ztunnel
COPY ztunnel/LICENSE /LICENSE

FROM ${CALICO_BASE}

ARG GIT_VERSION=unknown

# These labels are required for OCP Certification
LABEL description="This image contains a build of Istio's ztunnel component from github.com/istio/ztunnel with Calico patches applied"
LABEL maintainer="maintainers@tigera.io"
LABEL name="Calico Istio ztunnel"
LABEL release="1"
LABEL summary="ztunnel is the zero-trust tunnel component of Calico's integration with Istio ambient mesh"
LABEL vendor="Project Calico"
LABEL version="${GIT_VERSION}"

LABEL org.opencontainers.image.description="This image contains a build of Istio's ztunnel component from github.com/istio/ztunnel with Calico patches applied"
LABEL org.opencontainers.image.authors="maintainers@tigera.io"
LABEL org.opencontainers.image.source="https://github.com/projectcalico/calico"
LABEL org.opencontainers.image.title="ztunnel is the zero-trust tunnel component of Calico's integration with Istio ambient mesh"
LABEL org.opencontainers.image.vendor="Project Calico"
LABEL org.opencontainers.image.version="${GIT_VERSION}"
LABEL org.opencontainers.image.licenses="Apache-2.0"

COPY --from=source / /

USER 10001:10001

# Ztunnel default ports
# 15001: Outbound traffic interception
# 15006: Inbound traffic interception
# 15008: HBONE (HTTP-Based Overlay Network Environment) mTLS tunnel port
# 15020: Metrics and health checks
EXPOSE 15001 15006 15008 15020

ENTRYPOINT ["/usr/bin/ztunnel"]
