#!/usr/bin/env bash

set -x
set -e

if [ -z "${EL_VERSION}" ]; then
  echo "EL_VERSION variable should be set"
  exit 1
fi

repo=`pwd`
pkg=`basename $repo`
: "${RPM_TAR_ARGS:=}"

mkdir -p /tmp/rpmbuild/BUILD \
         /tmp/rpmbuild/RPMS \
         /tmp/rpmbuild/SOURCES \
         /tmp/rpmbuild/SPECS\
         /tmp/rpmbuild/SRPMS

# Copy the package spec into SPECS.
spec=`basename ${repo}/rpm/*.spec`
cp -a ${repo}/rpm/$spec /tmp/rpmbuild/SPECS/

# Link patches into ../SOURCES.
cd /tmp/rpmbuild/SOURCES
for f in ${repo}/rpm/*; do ln -sf $f; done

# Infer the version that the spec wants to build.
version=`grep Version: $spec | head -1 | awk '{print $2;}'`

case ${pkg} in
    calicoctl | felix | networking-calico )
	# Tar up the Git source, with the naming that rpmbuild expects.
	dir=${pkg}-${version}
	cp -a ${repo} /tmp/$dir
	tar -C /tmp \
	    --exclude-vcs \
	    ${RPM_TAR_ARGS} \
	    -czf /tmp/rpmbuild/SOURCES/${dir}.tar.gz $dir
	;;
    *)
	echo "ERROR: no source rule for package \"${pkg}\""
	exit 1
	;;
esac

# Build.  `dist` is set explicitly, rather than left to the build host, so that
# the RPM names carry .el8 and not the rebuild's own dist tag.
cd /tmp/rpmbuild
rpmbuild --target=$(uname -m) --define '_topdir '`pwd` --define "dist .${EL_VERSION}" -ba SPECS/${spec}
mkdir -p /code/release/packaging/output/dist/rpms-${EL_VERSION}/src
cp -r /tmp/rpmbuild/RPMS/* /code/release/packaging/output/dist/rpms-${EL_VERSION}/
cp -r /tmp/rpmbuild/SRPMS/* /code/release/packaging/output/dist/rpms-${EL_VERSION}/src/
