#!/bin/sh
not_ready_msg="calico/node is not ready"

# Check felix readiness
if [ "$FELIX_HEALTHENABLED" = "true" ]; then
    /usr/bin/wget -T 5 localhost:9099/readiness -O - &> /dev/null
    if [ $? -ge 400 ] || [ $? -lt 200 ]; then
        echo "$not_ready_msg: felix is not ready"
        exit 1
    fi
fi

# Check bird peer status
unestablished_peers()
{
    /bin/birdcl -s /var/run/calico/bird.ctl show protocols | tail -n +3 | while read -r line; do
        protocol=`echo "$line" | awk '{print $2}'`
        if [ "$protocol" != "BGP" ]; then
            continue
        fi

        status=`echo $line | awk '{print $6}'`
        if [ "$status" != "Established" ]; then
            peer=`echo $line | awk '{print $1}'`
            printf "$peer "
        fi
    done
}
# Check that bird is enabled.
if [ -d /etc/service/enabled/bird ]; then
    ueps=$(unestablished_peers)
    if [ ! -z "$ueps" ]; then
        echo "$not_ready_msg: BGP not established with $ueps"
        exit 1
    fi
fi

# Check bird is running
bird_status=$(/bin/birdcl -s /var/run/calico/bird.ctl show status)
if [ $? -gt 0 ]; then
    echo "$not_ready_msg: BGP daemon is not running yet."
    exit 1
fi

# Check bird GR status
if [ $(echo $bird_status | grep "Graceful restart recovery in progress") ]; then
    echo "$not_ready_msg: BGP Graceful restart in progress."
    exit 1
fi

echo "calico/node is ready."
