FROM golang:1.7

# These are only required for running the tests in a container.
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega

WORKDIR /go/src/github.com/projectcalico/calico/calico_upgrade
