// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DatastoreMigrationLister helps list DatastoreMigrations.
// All objects returned here must be treated as read-only.
type DatastoreMigrationLister interface {
	// List lists all DatastoreMigrations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.DatastoreMigration, err error)
	// Get retrieves the DatastoreMigration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalicov3.DatastoreMigration, error)
	DatastoreMigrationListerExpansion
}

// datastoreMigrationLister implements the DatastoreMigrationLister interface.
type datastoreMigrationLister struct {
	listers.ResourceIndexer[*projectcalicov3.DatastoreMigration]
}

// NewDatastoreMigrationLister returns a new DatastoreMigrationLister.
func NewDatastoreMigrationLister(indexer cache.Indexer) DatastoreMigrationLister {
	return &datastoreMigrationLister{listers.New[*projectcalicov3.DatastoreMigration](indexer, projectcalicov3.Resource("datastoremigration"))}
}
