// Copyright (c) 2025 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPAMBlockLister helps list IPAMBlocks.
// All objects returned here must be treated as read-only.
type IPAMBlockLister interface {
	// List lists all IPAMBlocks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.IPAMBlock, err error)
	// IPAMBlocks returns an object that can list and get IPAMBlocks.
	IPAMBlocks(namespace string) IPAMBlockNamespaceLister
	IPAMBlockListerExpansion
}

// iPAMBlockLister implements the IPAMBlockLister interface.
type iPAMBlockLister struct {
	listers.ResourceIndexer[*projectcalicov3.IPAMBlock]
}

// NewIPAMBlockLister returns a new IPAMBlockLister.
func NewIPAMBlockLister(indexer cache.Indexer) IPAMBlockLister {
	return &iPAMBlockLister{listers.New[*projectcalicov3.IPAMBlock](indexer, projectcalicov3.Resource("ipamblock"))}
}

// IPAMBlocks returns an object that can list and get IPAMBlocks.
func (s *iPAMBlockLister) IPAMBlocks(namespace string) IPAMBlockNamespaceLister {
	return iPAMBlockNamespaceLister{listers.NewNamespaced[*projectcalicov3.IPAMBlock](s.ResourceIndexer, namespace)}
}

// IPAMBlockNamespaceLister helps list and get IPAMBlocks.
// All objects returned here must be treated as read-only.
type IPAMBlockNamespaceLister interface {
	// List lists all IPAMBlocks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.IPAMBlock, err error)
	// Get retrieves the IPAMBlock from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalicov3.IPAMBlock, error)
	IPAMBlockNamespaceListerExpansion
}

// iPAMBlockNamespaceLister implements the IPAMBlockNamespaceLister
// interface.
type iPAMBlockNamespaceLister struct {
	listers.ResourceIndexer[*projectcalicov3.IPAMBlock]
}
