// Copyright (c) 2022 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	v3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IPAMConfigLister helps list IPAMConfigs.
// All objects returned here must be treated as read-only.
type IPAMConfigLister interface {
	// List lists all IPAMConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v3.IPAMConfig, err error)
	// Get retrieves the IPAMConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v3.IPAMConfig, error)
	IPAMConfigListerExpansion
}

// iPAMConfigLister implements the IPAMConfigLister interface.
type iPAMConfigLister struct {
	indexer cache.Indexer
}

// NewIPAMConfigLister returns a new IPAMConfigLister.
func NewIPAMConfigLister(indexer cache.Indexer) IPAMConfigLister {
	return &iPAMConfigLister{indexer: indexer}
}

// List lists all IPAMConfigs in the indexer.
func (s *iPAMConfigLister) List(selector labels.Selector) (ret []*v3.IPAMConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v3.IPAMConfig))
	})
	return ret, err
}

// Get retrieves the IPAMConfig from the index for a given name.
func (s *iPAMConfigLister) Get(name string) (*v3.IPAMConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v3.Resource("ipamconfig"), name)
	}
	return obj.(*v3.IPAMConfig), nil
}
