// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Code generated by lister-gen. DO NOT EDIT.

package v3

import (
	projectcalicov3 "github.com/projectcalico/api/pkg/apis/projectcalico/v3"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ProfileLister helps list Profiles.
// All objects returned here must be treated as read-only.
type ProfileLister interface {
	// List lists all Profiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.Profile, err error)
	// Profiles returns an object that can list and get Profiles.
	Profiles(namespace string) ProfileNamespaceLister
	ProfileListerExpansion
}

// profileLister implements the ProfileLister interface.
type profileLister struct {
	listers.ResourceIndexer[*projectcalicov3.Profile]
}

// NewProfileLister returns a new ProfileLister.
func NewProfileLister(indexer cache.Indexer) ProfileLister {
	return &profileLister{listers.New[*projectcalicov3.Profile](indexer, projectcalicov3.Resource("profile"))}
}

// Profiles returns an object that can list and get Profiles.
func (s *profileLister) Profiles(namespace string) ProfileNamespaceLister {
	return profileNamespaceLister{listers.NewNamespaced[*projectcalicov3.Profile](s.ResourceIndexer, namespace)}
}

// ProfileNamespaceLister helps list and get Profiles.
// All objects returned here must be treated as read-only.
type ProfileNamespaceLister interface {
	// List lists all Profiles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*projectcalicov3.Profile, err error)
	// Get retrieves the Profile from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*projectcalicov3.Profile, error)
	ProfileNamespaceListerExpansion
}

// profileNamespaceLister implements the ProfileNamespaceLister
// interface.
type profileNamespaceLister struct {
	listers.ResourceIndexer[*projectcalicov3.Profile]
}
