// Copyright (c) 2026 Tigera, Inc. All rights reserved.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli/v3"
)

const (
	// bundleDir is where 'operator-sdk generate bundle' leaves its output, and
	// where the rearranged, versioned bundle is written.
	bundleDir = "bundle"

	// bundleDockerfile is the Dockerfile that 'operator-sdk generate bundle'
	// writes, relative to the operator directory.
	bundleDockerfile = "bundle.Dockerfile"

	// csvName is the name of the ClusterServiceVersion within a bundle.
	csvName = "tigera-operator.clusterserviceversion.yaml"

	// openShiftVersions is the range of OpenShift versions the bundle supports.
	// Specify min version.
	openShiftVersions = "v4.16-v4.18"

	// noPreviousVersion is the value PREV_VERSION takes when this version
	// replaces nothing.
	noPreviousVersion = "0.0.0"
)

// metricsAnnotation is the operator-sdk metrics annotation, which a certified
// bundle must not carry.
var metricsAnnotation = regexp.MustCompile(`operators\.operatorframework\.io\.metrics`)

// bundleCopy matches the COPY directives that point at the pre-rearrange bundle
// layout, which are replaced with ones pointing at the versioned directories.
var bundleCopy = regexp.MustCompile(`^COPY bundle/(manifests|metadata)`)

var updateBundleCommand = &cli.Command{
	Name:  "update-bundle",
	Usage: "Apply the build-time values to a bundle generated by 'operator-sdk generate bundle' so that we can certify it",
	Description: "Everything static lives in config/manifests/bases/" + csvName + ", which operator-sdk reads as the base\n" +
		"for the generated CSV. Only values that cannot be known until build time belong here: image digests, the version,\n" +
		"what it replaces, the build timestamp, and the architectures the image was built for. If you find yourself adding\n" +
		"a constant, put it in the base instead.",
	Flags: []cli.Flag{versionFlag, prevVersionFlag, imageFlag, imageInspectFlag, manifestInspectFlag},
	Action: func(ctx context.Context, c *cli.Command) error {
		version := c.String(versionFlag.Name)
		repository := c.String(imageFlag.Name)
		inspected, err := inspectImage(ctx, repository, fmt.Sprintf("%s:v%s", repository, version),
			c.String(imageInspectFlag.Name), c.String(manifestInspectFlag.Name))
		if err != nil {
			return err
		}
		return updateBundle(version, c.String(prevVersionFlag.Name), inspected)
	},
}

// image holds the build-time facts about the operator image that the CSV records.
type image struct {
	// digest is the digest-pinned reference to the operator image.
	digest string
	// created is the time the image was built.
	created string
	// architectures are the architectures the image was built for.
	architectures []string
}

// inspectImage asks docker about the operator image the bundle is being built
// for. The two inspections can be passed in instead, which is what CI does when
// it has already run the docker commands elsewhere.
func inspectImage(ctx context.Context, repository, ref, imageInspect, manifestInspect string) (image, error) {
	// Both inspections read the image as the registry holds it, so pull it first
	// unless everything we need was passed in.
	if imageInspect == "" || manifestInspect == "" {
		logrus.Infof("Pulling operator image %s", ref)
		if _, err := docker(ctx, "pull", ref); err != nil {
			return image{}, err
		}
	}

	if imageInspect == "" {
		logrus.Infof("Getting operator image digest from %s", ref)
		out, err := docker(ctx, "image", "inspect", ref)
		if err != nil {
			return image{}, err
		}
		imageInspect = out
	}
	img, err := parseImageInspect(imageInspect, repository)
	if err != nil {
		return image{}, err
	}

	if manifestInspect == "" {
		logrus.Infof("Getting operator image architectures from %s", ref)
		out, err := docker(ctx, "manifest", "inspect", ref)
		if err != nil {
			return image{}, err
		}
		manifestInspect = out
	}
	img.architectures, err = parseArchitectures(manifestInspect)
	if err != nil {
		return image{}, err
	}
	return img, nil
}

// docker runs a docker command and returns its standard output. The commands
// run on the host rather than in the build container, which has no
// docker-in-docker.
func docker(ctx context.Context, args ...string) (string, error) {
	var stdout, stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("docker %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(stderr.String()))
	}
	return stdout.String(), nil
}

func updateBundle(version, prevVersion string, img image) error {
	versionDir := filepath.Join(bundleDir, version)
	if err := rearrangeBundle(versionDir); err != nil {
		return err
	}
	if err := updateCSV(filepath.Join(versionDir, "manifests", csvName), version, prevVersion, img); err != nil {
		return err
	}
	if err := updateDockerfile(version); err != nil {
		return err
	}
	return updateAnnotations(filepath.Join(versionDir, "metadata", "annotations.yaml"))
}

// rearrangeBundle moves the manifests and metadata that operator-sdk generated
// into a directory named for the version they belong to.
func rearrangeBundle(versionDir string) error {
	if err := os.RemoveAll(versionDir); err != nil {
		return fmt.Errorf("clearing %s: %w", versionDir, err)
	}
	if err := os.MkdirAll(versionDir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", versionDir, err)
	}
	for _, name := range []string{"manifests", "metadata"} {
		src := filepath.Join(bundleDir, name)
		if err := os.Rename(src, filepath.Join(versionDir, name)); err != nil {
			return fmt.Errorf("moving %s into %s: %w", src, versionDir, err)
		}
	}
	return nil
}

// csvUpdate is one build-time value written into the generated CSV.
type csvUpdate struct {
	path  []any
	value string
}

func updateCSV(path, version, prevVersion string, img image) error {
	csv, err := loadDocument(path)
	if err != nil {
		return err
	}

	// Record the digest-pinned operator image and the time it was built, and set
	// the CSV to ignore previous versions when updating.
	updates := []csvUpdate{
		{[]any{"metadata", "annotations", "containerImage"}, img.digest},
		{[]any{"metadata", "annotations", "createdAt"}, img.created},
		{[]any{"metadata", "annotations", "olm.skipRange"}, "<" + version},
	}

	// Add labels for each supported architecture, e.g.
	// operatorframework.io/arch.arm64: supported. At least amd64 is needed so
	// that we can use the SHA256 of the manifest image rather than the specific
	// SHA of the amd64 image.
	for _, arch := range img.architectures {
		updates = append(updates, csvUpdate{[]any{"metadata", "labels", "operatorframework.io/arch." + arch}, "supported"})
	}

	// The display name carries the release stream so that the channels are
	// distinguishable in OperatorHub, e.g. "Tigera Operator v1.42" for 1.42.6.
	updates = append(updates, csvUpdate{[]any{"spec", "displayName"}, "Tigera Operator v" + releaseStream(version)})

	// Set the previous version of the operator that this version replaces.
	if prevVersion != noPreviousVersion {
		updates = append(updates, csvUpdate{[]any{"spec", "replaces"}, "tigera-operator.v" + prevVersion})
	}

	// Pin the operator image by digest, both in the deployment spec embedded in
	// the CSV and in the 'relatedImages' list that a certified bundle must carry.
	updates = append(updates,
		csvUpdate{[]any{"spec", "install", "spec", "deployments", 0, "spec", "template", "spec", "containers", 0, "image"}, img.digest},
		csvUpdate{[]any{"spec", "relatedImages", 0, "name"}, "tigera-operator"},
		csvUpdate{[]any{"spec", "relatedImages", 0, "image"}, img.digest},
	)

	for _, u := range updates {
		logrus.Debugf("Setting %s = %q", pathString(u.path), u.value)
		if err := csv.set(u.value, u.path...); err != nil {
			return fmt.Errorf("updating %s: %w", path, err)
		}
	}

	// Delete empty permissions (we only set clusterPermissions) otherwise the
	// CSV validation fails.
	if err := csv.delete("spec", "install", "spec", "permissions"); err != nil {
		return fmt.Errorf("updating %s: %w", path, err)
	}

	logrus.Infof("Updated %s", path)
	return csv.save()
}

// releaseStream returns the X.Y stream that an X.Y.Z version belongs to.
func releaseStream(version string) string {
	if i := strings.LastIndex(version, "."); i >= 0 {
		return version[:i]
	}
	return version
}

func updateDockerfile(version string) error {
	err := editLines(bundleDockerfile, func(lines []string) []string {
		// Add in required labels.
		lines = append(lines,
			fmt.Sprintf("LABEL com.redhat.openshift.versions=%q", openShiftVersions),
			"LABEL com.redhat.delivery.backport=true",
			"LABEL com.redhat.delivery.operator.bundle=true",
		)
		// Remove unneeded labels, and fix the bundle path.
		lines = filterLines(lines, func(line string) bool {
			return metricsAnnotation.MatchString(line) || bundleCopy.MatchString(line)
		})
		lines = append(lines,
			fmt.Sprintf("COPY %s/manifests /manifests/", version),
			fmt.Sprintf("COPY %s/metadata /metadata/", version),
		)
		// Remove unneeded empty lines.
		return filterLines(lines, func(line string) bool { return line == "" })
	})
	if err != nil {
		return err
	}

	// Lastly move the dockerfile to the bundle dir, renaming it with the version.
	dst := filepath.Join(bundleDir, fmt.Sprintf("bundle-v%s.Dockerfile", version))
	if err := os.Rename(bundleDockerfile, dst); err != nil {
		return fmt.Errorf("moving %s to %s: %w", bundleDockerfile, dst, err)
	}
	logrus.Infof("Updated %s", dst)
	return nil
}

func updateAnnotations(path string) error {
	err := editLines(path, func(lines []string) []string {
		// Remove unneeded labels and empty lines.
		lines = filterLines(lines, func(line string) bool {
			return line == "" || metricsAnnotation.MatchString(line)
		})
		// Add required com.redhat.openshift.versions.
		return append(lines, fmt.Sprintf("  com.redhat.openshift.versions: %s", openShiftVersions))
	})
	if err != nil {
		return err
	}
	logrus.Infof("Updated %s", path)
	return nil
}

// parseImageInspect pulls the digest-pinned operator image and its build time
// out of 'docker image inspect' output, which looks like:
//
//	[
//	    {
//	        "Id": "sha256:...",
//	        "RepoTags": [
//	            "quay.io/tigera/operator:v1.3.1",
//	            "..."
//	        ],
//	        "RepoDigests": [
//	            "quay.io/tigera/operator@sha256:5e1d551b5a711592472f4a...",
//	            "..."
//	        ],
//	        ...
//	    }
//	]
//
// RepoDigests may have more than one entry, so we filter for the repository the
// bundle is being built from.
func parseImageInspect(content, repository string) (image, error) {
	var inspected []struct {
		Created     string   `json:"Created"`
		RepoDigests []string `json:"RepoDigests"`
	}
	if err := parseJSON(content, &inspected); err != nil {
		return image{}, fmt.Errorf("reading image inspect output: %w", err)
	}
	if len(inspected) == 0 {
		return image{}, fmt.Errorf("image inspect output is empty")
	}
	for _, digest := range inspected[0].RepoDigests {
		if strings.Contains(digest, repository) {
			return image{digest: digest, created: inspected[0].Created}, nil
		}
	}
	return image{}, fmt.Errorf("no %s digest in image inspect output", repository)
}

// parseArchitectures lists the architectures the image was built for, from
// 'docker manifest inspect' output.
func parseArchitectures(content string) ([]string, error) {
	var inspected struct {
		Manifests []struct {
			Platform struct {
				Architecture string `json:"architecture"`
			} `json:"platform"`
		} `json:"manifests"`
	}
	if err := parseJSON(content, &inspected); err != nil {
		return nil, fmt.Errorf("reading manifest inspect output: %w", err)
	}
	architectures := make([]string, 0, len(inspected.Manifests))
	for _, manifest := range inspected.Manifests {
		architectures = append(architectures, manifest.Platform.Architecture)
	}
	if len(architectures) == 0 {
		return nil, fmt.Errorf("no architectures in manifest inspect output")
	}
	return architectures, nil
}

// parseJSON reads docker inspect output, which an override may have passed
// base64-encoded so that it survives a trip through the environment.
func parseJSON(content string, into any) error {
	content = strings.TrimSpace(content)
	if !strings.HasPrefix(content, "[") && !strings.HasPrefix(content, "{") {
		decoded, err := base64.StdEncoding.DecodeString(content)
		if err != nil {
			return err
		}
		content = string(decoded)
	}
	return json.Unmarshal([]byte(content), into)
}
