#!/usr/bin/env bash

# Copyright (c) 2020 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# No set -e so that we continue to collect artifacts even if some fail.
set -x

my_dir=$(dirname "$0")
repo_dir=$my_dir/..

cd "$repo_dir/artifacts" || exit 1

for file in *; do
  artifact push job "$file"
done
